# Copyright (c) Meta Platforms, Inc. and affiliates.

# pyre-unsafe

import json
from typing import List

from ixia.ixia import types as ixia_thrift
from taac.testconfigs.configerator.packet_headers import (
    BGP_CP_TRAFFIC_PACKET_HEADERS,
    DHCP_V6_TRAFFIC_PACKET_HEADERS,
    HOP_LIMIT_0_IPV6_TRAFFIC_PACKET_HEADERS,
    HOP_LIMIT_1_IPV6_TRAFFIC_PACKET_HEADERS,
    ICMP_V6_REQUEST_TRAFFIC_PACKET_HEADERS,
    LACP_SLOW_TIMER_TRAFFIC_PACKET_HEADERS,
    LLDP_TRAFFIC_PACKET_HEADERS,
)
from taac.testconfigs.configerator.test_config import (
    thrift_to_json,
)
from taac.health_check.health_check import types as hc_thrift
from taac.test_as_a_config import types as taac_thrift

DEFAULT_LOW_QUEUE = 0
DEFAULT_MID_QUEUE = 2
DEFAULT_HIGH_QUEUE = 9  # can be 7 for some hosts


def create_cpu_queue_test_config(
    test_config_name: str,
    hostname: str,
    ingress_ixia_port: str,
    egress_ixia_port: str,
    mac_address: str,
    basic_port_configs: List[taac_thrift.BasicPortConfig],
    basset_pool: str = "dne.test",
    low_queue: int = DEFAULT_LOW_QUEUE,
    mid_queue: int = DEFAULT_MID_QUEUE,
    high_queue: int = DEFAULT_HIGH_QUEUE,
) -> taac_thrift.TestConfig:
    return taac_thrift.TestConfig(
        name=test_config_name,
        basset_pool=basset_pool,
        ignore_circuit_fbnet_status=True,
        endpoints=[
            taac_thrift.Endpoint(
                name=hostname,
                dut=True,
                ixia_ports=[ingress_ixia_port, egress_ixia_port],
                mac_address=mac_address,
            ),
        ],
        postchecks=[
            taac_thrift.PointInTimeHealthCheck(
                name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                input_json=thrift_to_json(
                    hc_thrift.IxiaPacketLossHealthCheckIn(
                        thresholds=[hc_thrift.PacketLossThreshold(str_value="0.1")]
                    )
                ),
            ),
            taac_thrift.PointInTimeHealthCheck(
                name=hc_thrift.CheckName.UNCLEAN_EXIT_CHECK,
                check_params=taac_thrift.Params(
                    jq_params={
                        "start_time": ".test_case_start_time",
                    }
                ),
            ),
        ],
        prechecks=[
            taac_thrift.PointInTimeHealthCheck(
                name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                input_json=thrift_to_json(
                    hc_thrift.IxiaPacketLossHealthCheckIn(
                        thresholds=[hc_thrift.PacketLossThreshold(str_value="0.1")]
                    )
                ),
            ),
        ],
        snapshot_checks=[
            taac_thrift.SnapshotHealthCheck(name=hc_thrift.CheckName.CORE_DUMPS_CHECK)
        ],
        basic_traffic_item_configs=[
            taac_thrift.BasicTrafficItemConfig(
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                name="TEST_NEXTHOP_LIMIT_1_IPV6_TRAFFIC",
                line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
                line_rate=2000,
                traffic_type=ixia_thrift.TrafficType.RAW,
                bidirectional=False,
                packet_headers=HOP_LIMIT_1_IPV6_TRAFFIC_PACKET_HEADERS,
            ),
            taac_thrift.BasicTrafficItemConfig(
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                name="TEST_NEXTHOP_LIMIT_0_IPV6_TRAFFIC",
                line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
                line_rate=2000,
                traffic_type=ixia_thrift.TrafficType.RAW,
                bidirectional=False,
                packet_headers=HOP_LIMIT_0_IPV6_TRAFFIC_PACKET_HEADERS,
            ),
            taac_thrift.BasicTrafficItemConfig(
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                name="TEST_LACP_SLOW_TIMER_TRAFFIC",
                line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
                line_rate=2000,
                traffic_type=ixia_thrift.TrafficType.RAW,
                bidirectional=False,
                packet_headers=LACP_SLOW_TIMER_TRAFFIC_PACKET_HEADERS,
            ),
            taac_thrift.BasicTrafficItemConfig(
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                name="TEST_RAW_DHCP_V6_TRAFFIC",
                line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
                line_rate=2000,
                traffic_type=ixia_thrift.TrafficType.RAW,
                bidirectional=False,
                packet_headers=DHCP_V6_TRAFFIC_PACKET_HEADERS,
            ),
            taac_thrift.BasicTrafficItemConfig(
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                name="TEST_RAW_ICMP_V6_REQUEST_TRAFFIC",
                line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
                line_rate=2000,
                traffic_type=ixia_thrift.TrafficType.RAW,
                bidirectional=False,
                packet_headers=ICMP_V6_REQUEST_TRAFFIC_PACKET_HEADERS,
            ),
            taac_thrift.BasicTrafficItemConfig(
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                name="TEST_RAW_BGP_CP_TRAFFIC",
                line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
                line_rate=2000,
                traffic_type=ixia_thrift.TrafficType.RAW,
                bidirectional=False,
                packet_headers=BGP_CP_TRAFFIC_PACKET_HEADERS,
            ),
            taac_thrift.BasicTrafficItemConfig(
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                name="TEST_RAW_LLDP_TRAFFIC",
                line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
                line_rate=2000,
                traffic_type=ixia_thrift.TrafficType.RAW,
                bidirectional=False,
                packet_headers=LLDP_TRAFFIC_PACKET_HEADERS,
            ),
            taac_thrift.BasicTrafficItemConfig(
                name="BGP_PREFIX_TRAFFIC",
                bidirectional=False,
                merge_destinations=True,
                line_rate=10,
                src_dest_mesh=ixia_thrift.SrcDestMeshType.MANY_TO_MANY,
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                        network_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                        network_group_index=0,
                    ),
                ],
                traffic_type=ixia_thrift.TrafficType.IPV6,
                frame_size_settings=ixia_thrift.FrameSize(
                    type=ixia_thrift.FrameSizeType.CUSTOM_IMIX
                ),
            ),
            taac_thrift.BasicTrafficItemConfig(
                name="IPV6_TRAFFIC",
                bidirectional=False,
                merge_destinations=True,
                line_rate=10,
                src_dest_mesh=ixia_thrift.SrcDestMeshType.MANY_TO_MANY,
                src_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{ingress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    taac_thrift.TrafficEndpoint(
                        name=f"{hostname}:{egress_ixia_port}",
                        device_group_index=0,
                    ),
                ],
                traffic_type=ixia_thrift.TrafficType.IPV6,
                frame_size_settings=ixia_thrift.FrameSize(
                    type=ixia_thrift.FrameSizeType.CUSTOM_IMIX
                ),
            ),
        ],
        basic_port_configs=basic_port_configs,
        playbooks=[
            taac_thrift.Playbook(
                name="test_lacp_traffic_punted_to_cpu_high_queue",
                traffic_items_to_start=[
                    "TEST_LACP_SLOW_TIMER_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            )
                        ],
                    )
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[high_queue],
                                no_discard_queues=[high_queue],
                                active_min_out_pps_per_queue={low_queue: 10},
                            )
                        ),
                    )
                ],
            ),
            taac_thrift.Playbook(
                name="test_nexthop_limit_1_punted_to_cpu_low_queue",
                traffic_items_to_start=[
                    "TEST_NEXTHOP_LIMIT_1_IPV6_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            )
                        ],
                    )
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[low_queue],
                                no_discard_queues=[mid_queue, high_queue],
                                active_min_out_pps_per_queue={low_queue: 10},
                            )
                        ),
                    )
                ],
            ),
            taac_thrift.Playbook(
                name="test_nexthop_limit_0_not_punted_to_cpu",
                traffic_items_to_start=[
                    "TEST_NEXTHOP_LIMIT_0_IPV6_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            )
                        ],
                    )
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[],
                                no_discard_queues=[low_queue, mid_queue, high_queue],
                                active_min_out_pps_per_queue={low_queue: 10},
                            )
                        ),
                    )
                ],
            ),
            taac_thrift.Playbook(
                name="test_icmp_v6_request_traffic_punted_to_cpu_mid_queue",
                traffic_items_to_start=[
                    "TEST_RAW_ICMP_V6_REQUEST_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            )
                        ],
                    )
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[mid_queue],
                                no_discard_queues=[high_queue],
                                active_min_out_pps_per_queue={low_queue: 10},
                            )
                        ),
                    )
                ],
            ),
            taac_thrift.Playbook(
                name="test_dhcp_v6_traffic_punted_to_cpu_mid_queue",
                traffic_items_to_start=[
                    "TEST_RAW_DHCP_V6_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            )
                        ],
                    )
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[mid_queue],
                                no_discard_queues=[high_queue],
                                active_min_out_pps_per_queue={low_queue: 10},
                            )
                        ),
                    )
                ],
            ),
            taac_thrift.Playbook(
                name="test_lldp_traffic_punted_to_cpu_mid_queue",
                traffic_items_to_start=[
                    "TEST_RAW_LLDP_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            )
                        ],
                    )
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[mid_queue],
                                no_discard_queues=[high_queue],
                                active_min_out_pps_per_queue={low_queue: 10},
                            )
                        ),
                    )
                ],
            ),
            taac_thrift.Playbook(
                name="test_bgp_cp_traffic_punted_to_cpu_high_queue",
                traffic_items_to_start=[
                    "TEST_RAW_BGP_CP_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            )
                        ],
                    )
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[high_queue],
                                no_discard_queues=[high_queue],
                                active_min_out_pps_per_queue={low_queue: 10},
                            )
                        ),
                    )
                ],
            ),
            taac_thrift.Playbook(
                name="test_cpu_mid_queue_warmboot",
                traffic_items_to_start=[
                    "TEST_RAW_LLDP_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        id="test_cpu_mid_queue_warmboot",
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                id="do_warmboot",
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                id="wait_for_agent_configured_state",
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                        ],
                    ),
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[mid_queue],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        post_snapshot_checkpoint_id="stage.test_cpu_mid_queue_warmboot.step.do_warmboot.start",
                    ),
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[mid_queue],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_cpu_mid_queue_warmboot.step.wait_for_agent_configured_state.end",
                    ),
                ],
            ),
            taac_thrift.Playbook(
                name="test_cpu_high_queue_warmboot",
                traffic_items_to_start=[
                    "TEST_RAW_BGP_CP_TRAFFIC",
                    "BGP_PREFIX_TRAFFIC",
                ],
                stages=[
                    taac_thrift.Stage(
                        id="test_cpu_high_queue_warmboot",
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                id="do_warmboot",
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                id="wait_for_agent_configured_state",
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                        ],
                    ),
                ],
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[high_queue],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        post_snapshot_checkpoint_id="stage.test_cpu_high_queue_warmboot.step.do_warmboot.start",
                    ),
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[high_queue],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_cpu_high_queue_warmboot.step.wait_for_agent_configured_state.end",
                    ),
                ],
            ),
            taac_thrift.Playbook(
                postchecks=[
                    taac_thrift.PointInTimeHealthCheck(
                        name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.IxiaPacketLossHealthCheckIn(
                                clear_traffic_stats=True,
                            )
                        ),
                    )
                ],
                traffic_items_to_start=["BGP_PREFIX_TRAFFIC"],
                name="test_fboss_cpu_remote_subnet_unh",
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[low_queue],
                                no_discard_queues=[mid_queue, high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_unh.step.disable_next_hop_egress_port.end",
                        post_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_unh.step.enable_next_hop_egress_port.start",
                    ),
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_unh.step.enable_next_hop_egress_port.end",
                    ),
                ],
                stages=[
                    taac_thrift.Stage(
                        id="test_fboss_cpu_remote_subnet_unh",
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.CUSTOM_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "custom_step_name": "register_cpu_queue_static_route_patcher",
                                            "static_route_mask": 64,
                                            "next_hop_egress_port": egress_ixia_port,
                                            "patcher_name": "cpu_queue_static_route_patcher",
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                            taac_thrift.Step(
                                id="disable_next_hop_egress_port",
                                name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "enable": False,
                                            "interface_flap_method": 1,
                                            "interfaces": [egress_ixia_port],
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                id="enable_next_hop_egress_port",
                                name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "enable": True,
                                            "interface_flap_method": 1,
                                            "interfaces": [egress_ixia_port],
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.REGISTER_PATCHER_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.RegisterPatcherInput(
                                        register_patcher=False,
                                        name="cpu_queue_static_route_patcher",
                                        config_name="agent",
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                        ],
                    )
                ],
            ),
            taac_thrift.Playbook(
                postchecks=[
                    taac_thrift.PointInTimeHealthCheck(
                        name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.IxiaPacketLossHealthCheckIn(
                                clear_traffic_stats=True,
                            )
                        ),
                    )
                ],
                traffic_items_to_start=["BGP_PREFIX_TRAFFIC"],
                name="test_fboss_cpu_remote_subnet_128_unh",
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[mid_queue],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_128_unh.step.disable_next_hop_egress_port.end",
                        post_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_128_unh.step.enable_next_hop_egress_port.start",
                    ),
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_128_unh.step.enable_next_hop_egress_port.end",
                    ),
                ],
                stages=[
                    taac_thrift.Stage(
                        id="test_fboss_cpu_remote_subnet_128_unh",
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.CUSTOM_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "custom_step_name": "register_cpu_queue_static_route_patcher",
                                            "static_route_mask": 128,
                                            "next_hop_egress_port": egress_ixia_port,
                                            "patcher_name": "cpu_queue_static_route_patcher",
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                            taac_thrift.Step(
                                id="disable_next_hop_egress_port",
                                name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "enable": False,
                                            "interface_flap_method": 1,
                                            "interfaces": [egress_ixia_port],
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                id="enable_next_hop_egress_port",
                                name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "enable": True,
                                            "interface_flap_method": 1,
                                            "interfaces": [egress_ixia_port],
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.REGISTER_PATCHER_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.RegisterPatcherInput(
                                        register_patcher=False,
                                        name="cpu_queue_static_route_patcher",
                                        config_name="agent",
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                        ],
                    )
                ],
            ),
            taac_thrift.Playbook(
                postchecks=[
                    taac_thrift.PointInTimeHealthCheck(
                        name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.IxiaPacketLossHealthCheckIn(
                                clear_traffic_stats=True,
                            )
                        ),
                    )
                ],
                traffic_items_to_start=["IPV6_TRAFFIC"],
                name="test_fboss_cpu_dir_conn_host_unh",
                snapshot_checks=[
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[low_queue],
                                no_discard_queues=[mid_queue, high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_fboss_cpu_dir_conn_host_unh.step.disable_next_hop_egress_port.end",
                        post_snapshot_checkpoint_id="stage.test_fboss_cpu_dir_conn_host_unh.step.enable_next_hop_egress_port.start",
                    ),
                    taac_thrift.SnapshotHealthCheck(
                        name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                        input_json=thrift_to_json(
                            hc_thrift.CpuQueueHealthCheckIn(
                                active_queues=[],
                                no_discard_queues=[high_queue],
                            )
                        ),
                        pre_snapshot_checkpoint_id="stage.test_fboss_cpu_dir_conn_host_unh.step.enable_next_hop_egress_port.end",
                    ),
                ],
                stages=[
                    taac_thrift.Stage(
                        id="test_fboss_cpu_dir_conn_host_unh",
                        steps=[
                            taac_thrift.Step(
                                name=taac_thrift.StepName.CUSTOM_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "custom_step_name": "register_cpu_queue_static_route_patcher",
                                            "static_route_mask": 64,
                                            "next_hop_egress_port": egress_ixia_port,
                                            "patcher_name": "cpu_queue_static_route_patcher",
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                            taac_thrift.Step(
                                id="disable_next_hop_egress_port",
                                name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "enable": False,
                                            "interface_flap_method": 1,
                                            "interfaces": [egress_ixia_port],
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                id="enable_next_hop_egress_port",
                                name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                                step_params=taac_thrift.Params(
                                    json_params=json.dumps(
                                        {
                                            "enable": True,
                                            "interface_flap_method": 1,
                                            "interfaces": [egress_ixia_port],
                                        }
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.LONGEVITY_STEP,
                                step_params=taac_thrift.Params(
                                    json_params='{"duration": 60}'
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.REGISTER_PATCHER_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.RegisterPatcherInput(
                                        register_patcher=False,
                                        name="cpu_queue_static_route_patcher",
                                        config_name="agent",
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                                input_json=thrift_to_json(
                                    taac_thrift.ServiceInterruptionInput(
                                        name=taac_thrift.Service.AGENT,
                                        trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                    )
                                ),
                            ),
                            taac_thrift.Step(
                                name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                            ),
                        ],
                    )
                ],
            ),
        ],
    )
