# Copyright (c) Meta Platforms, Inc. and affiliates.

# pyre-unsafe

import json

from ixia.ixia import types as ixia_thrift
from taac.testconfigs.configerator.packet_headers import (
    BGP_CP_TRAFFIC_PACKET_HEADERS,
    HOP_LIMIT_1_IPV6_TRAFFIC_PACKET_HEADERS,
    LLDP_TRAFFIC_PACKET_HEADERS,
)
from taac.testconfigs.configerator.test_config import (
    thrift_to_json,
)
from taac.health_check.health_check import types as hc_thrift
from taac.test_as_a_config import types as taac_thrift

LOW_QUEUE = 0
MID_QUEUE = 2
HIGH_QUEUE = 9

test_config = taac_thrift.TestConfig(
    name="GB_300_CPU",
    basset_pool="dne.test",
    ignore_circuit_fbnet_status=True,
    endpoints=[
        taac_thrift.Endpoint(
            name="rsw001.p001.m001.qzr1",
            dut=True,
            ixia_ports=["eth1/64/5", "eth1/64/1"],
            mac_address="b6:db:91:95:ff:4f",
        ),
    ],
    postchecks=[
        taac_thrift.PointInTimeHealthCheck(
            name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
            input_json=thrift_to_json(
                hc_thrift.IxiaPacketLossHealthCheckIn(
                    thresholds=[hc_thrift.PacketLossThreshold(str_value="0.1")]
                )
            ),
        ),
    ],
    prechecks=[
        taac_thrift.PointInTimeHealthCheck(
            name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
            input_json=thrift_to_json(
                hc_thrift.IxiaPacketLossHealthCheckIn(
                    thresholds=[hc_thrift.PacketLossThreshold(str_value="0.1")]
                )
            ),
        ),
    ],
    snapshot_checks=[
        taac_thrift.SnapshotHealthCheck(name=hc_thrift.CheckName.CORE_DUMPS_CHECK)
    ],
    basic_traffic_item_configs=[
        taac_thrift.BasicTrafficItemConfig(
            src_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/1",
                    device_group_index=0,
                ),
            ],
            dest_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/5",
                    device_group_index=0,
                ),
            ],
            name="TEST_NEXTHOP_LIMIT_1_IPV6_TRAFFIC",
            line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
            line_rate=2000,
            traffic_type=ixia_thrift.TrafficType.RAW,
            bidirectional=False,
            packet_headers=HOP_LIMIT_1_IPV6_TRAFFIC_PACKET_HEADERS,
        ),
        taac_thrift.BasicTrafficItemConfig(
            src_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/1",
                    device_group_index=0,
                ),
            ],
            dest_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/5",
                    device_group_index=0,
                ),
            ],
            name="TEST_RAW_BGP_CP_TRAFFIC",
            line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
            line_rate=2000,
            traffic_type=ixia_thrift.TrafficType.RAW,
            bidirectional=False,
            packet_headers=BGP_CP_TRAFFIC_PACKET_HEADERS,
        ),
        taac_thrift.BasicTrafficItemConfig(
            src_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/1",
                    device_group_index=0,
                ),
            ],
            dest_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/5",
                    device_group_index=0,
                ),
            ],
            name="TEST_RAW_LLDP_TRAFFIC",
            line_rate_type=ixia_thrift.RateType.FRAMES_PER_SECOND,
            line_rate=2000,
            traffic_type=ixia_thrift.TrafficType.RAW,
            bidirectional=False,
            packet_headers=LLDP_TRAFFIC_PACKET_HEADERS,
        ),
        taac_thrift.BasicTrafficItemConfig(
            name="BGP_PREFIX_TRAFFIC",
            bidirectional=False,
            merge_destinations=True,
            line_rate=10,
            src_dest_mesh=ixia_thrift.SrcDestMeshType.MANY_TO_MANY,
            src_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/1",
                    device_group_index=0,
                    network_group_index=0,
                ),
            ],
            dest_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/5",
                    device_group_index=0,
                    network_group_index=0,
                ),
            ],
            traffic_type=ixia_thrift.TrafficType.IPV6,
            frame_size_settings=ixia_thrift.FrameSize(
                type=ixia_thrift.FrameSizeType.CUSTOM_IMIX
            ),
        ),
        taac_thrift.BasicTrafficItemConfig(
            name="IPV6_TRAFFIC",
            bidirectional=False,
            merge_destinations=True,
            line_rate=10,
            src_dest_mesh=ixia_thrift.SrcDestMeshType.MANY_TO_MANY,
            src_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/1",
                    device_group_index=0,
                ),
            ],
            dest_endpoints=[
                taac_thrift.TrafficEndpoint(
                    name="rsw001.p001.m001.qzr1:eth1/64/5",
                    device_group_index=0,
                ),
            ],
            traffic_type=ixia_thrift.TrafficType.IPV6,
            frame_size_settings=ixia_thrift.FrameSize(
                type=ixia_thrift.FrameSizeType.CUSTOM_IMIX
            ),
        ),
    ],
    basic_port_configs=[
        taac_thrift.BasicPortConfig(
            device_group_configs=[
                taac_thrift.DeviceGroupConfig(
                    v6_addresses_config=taac_thrift.IpAddressesConfig(
                        starting_ip="2401:db00:e718::f:1:1"
                    ),
                    multiplier=10,
                    device_group_index=0,
                    v6_bgp_config=taac_thrift.BgpConfig(
                        local_as_4_bytes=6004,
                        is_confed=True,
                        route_scales=[
                            taac_thrift.RouteScaleSpec(
                                network_group_index=0,
                                v6_route_scale=taac_thrift.RouteScale(
                                    multiplier=10,
                                    prefix_count=1500,
                                    prefix_length=64,
                                    starting_prefixes="4000::",
                                    bgp_communities=["65529:51710"],
                                    prefix_step="0:0:0:0:1::",
                                    ip_address_family=ixia_thrift.IpAddressFamily.IPV6,
                                ),
                            ),
                        ],
                    ),
                )
            ],
            endpoint="rsw001.p001.m001.qzr1:eth1/64/5",
        ),
        taac_thrift.BasicPortConfig(
            device_group_configs=[
                taac_thrift.DeviceGroupConfig(
                    device_group_index=0,
                    multiplier=10,
                    v6_addresses_config=taac_thrift.IpAddressesConfig(
                        starting_ip="2401:db00:e717::e:1:1"
                    ),
                    v6_bgp_config=taac_thrift.BgpConfig(
                        local_as_4_bytes=6003,
                        is_confed=True,
                        route_scales=[
                            taac_thrift.RouteScaleSpec(
                                network_group_index=0,
                                v6_route_scale=taac_thrift.RouteScale(
                                    multiplier=10,
                                    prefix_count=1500,
                                    prefix_length=64,
                                    starting_prefixes="5000::",
                                    bgp_communities=["65529:51710"],
                                    prefix_step="0:0:0:0:1::",
                                    ip_address_family=ixia_thrift.IpAddressFamily.IPV6,
                                ),
                            ),
                        ],
                    ),
                )
            ],
            endpoint="rsw001.p001.m001.qzr1:eth1/64/1",
        ),
    ],
    playbooks=[
        taac_thrift.Playbook(
            name="test_nexthop_limit_1_punted_to_cpu_low_queue",
            traffic_items_to_start=[
                "TEST_NEXTHOP_LIMIT_1_IPV6_TRAFFIC",
            ],
            stages=[
                taac_thrift.Stage(
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        )
                    ],
                )
            ],
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[LOW_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                )
            ],
        ),
        taac_thrift.Playbook(
            name="test_cpu_high_queue_traffic",
            traffic_items_to_start=[
                "TEST_RAW_BGP_CP_TRAFFIC",
                "BGP_PREFIX_TRAFFIC",
            ],
            stages=[
                taac_thrift.Stage(
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        )
                    ],
                )
            ],
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[HIGH_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                            active_min_out_pps_per_queue={LOW_QUEUE: 10},
                        )
                    ),
                )
            ],
        ),
        taac_thrift.Playbook(
            name="test_cpu_mid_queue_traffic",
            traffic_items_to_start=[
                "TEST_RAW_LLDP_TRAFFIC",
                "BGP_PREFIX_TRAFFIC",
            ],
            stages=[
                taac_thrift.Stage(
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        )
                    ],
                )
            ],
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[MID_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                            active_min_out_pps_per_queue={LOW_QUEUE: 10},
                        )
                    ),
                )
            ],
        ),
        taac_thrift.Playbook(
            name="test_cpu_high_queue_traffic",
            traffic_items_to_start=[
                "TEST_RAW_BGP_CP_TRAFFIC",
                "BGP_PREFIX_TRAFFIC",
            ],
            stages=[
                taac_thrift.Stage(
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        )
                    ],
                )
            ],
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[HIGH_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                            active_min_out_pps_per_queue={LOW_QUEUE: 10},
                        )
                    ),
                )
            ],
        ),
        taac_thrift.Playbook(
            name="test_cpu_mid_queue_warmboot",
            traffic_items_to_start=[
                "TEST_RAW_LLDP_TRAFFIC",
                "BGP_PREFIX_TRAFFIC",
            ],
            stages=[
                taac_thrift.Stage(
                    id="test_cpu_mid_queue_warmboot",
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            id="do_warmboot",
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            id="wait_for_agent_configured_state",
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                    ],
                ),
            ],
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[MID_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    post_snapshot_checkpoint_id="stage.test_cpu_mid_queue_warmboot.step.do_warmboot.start",
                ),
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[MID_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_cpu_mid_queue_warmboot.step.wait_for_agent_configured_state.end",
                ),
            ],
        ),
        taac_thrift.Playbook(
            name="test_cpu_high_queue_warmboot",
            traffic_items_to_start=[
                "TEST_RAW_BGP_CP_TRAFFIC",
                "BGP_PREFIX_TRAFFIC",
            ],
            stages=[
                taac_thrift.Stage(
                    id="test_cpu_high_queue_warmboot",
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            id="do_warmboot",
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            id="wait_for_agent_configured_state",
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                    ],
                ),
            ],
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[HIGH_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    post_snapshot_checkpoint_id="stage.test_cpu_high_queue_warmboot.step.do_warmboot.start",
                ),
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[HIGH_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_cpu_high_queue_warmboot.step.wait_for_agent_configured_state.end",
                ),
            ],
        ),
        taac_thrift.Playbook(
            postchecks=[
                taac_thrift.PointInTimeHealthCheck(
                    name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.IxiaPacketLossHealthCheckIn(
                            clear_traffic_stats=True,
                        )
                    ),
                )
            ],
            traffic_items_to_start=["BGP_PREFIX_TRAFFIC"],
            name="test_fboss_cpu_remote_subnet_unh",
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[LOW_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_unh.step.disable_next_hop_egress_port.end",
                    post_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_unh.step.enable_next_hop_egress_port.start",
                ),
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_unh.step.enable_next_hop_egress_port.end",
                ),
            ],
            stages=[
                taac_thrift.Stage(
                    id="test_fboss_cpu_remote_subnet_unh",
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.CUSTOM_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "custom_step_name": "register_cpu_queue_static_route_patcher",
                                        "static_route_mask": 64,
                                        "next_hop_egress_port": "eth1/64/5",
                                        "patcher_name": "cpu_queue_static_route_patcher",
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                        taac_thrift.Step(
                            id="disable_next_hop_egress_port",
                            name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "enable": False,
                                        "interface_flap_method": 1,
                                        "interfaces": ["eth1/64/5"],
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            id="enable_next_hop_egress_port",
                            name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "enable": True,
                                        "interface_flap_method": 1,
                                        "interfaces": ["eth1/64/5"],
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.REGISTER_PATCHER_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.RegisterPatcherInput(
                                    register_patcher=False,
                                    name="cpu_queue_static_route_patcher",
                                    config_name="agent",
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                    ],
                )
            ],
        ),
        taac_thrift.Playbook(
            postchecks=[
                taac_thrift.PointInTimeHealthCheck(
                    name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.IxiaPacketLossHealthCheckIn(
                            clear_traffic_stats=True,
                        )
                    ),
                )
            ],
            traffic_items_to_start=["BGP_PREFIX_TRAFFIC"],
            name="test_fboss_cpu_remote_subnet_128_unh",
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[MID_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_128_unh.step.disable_next_hop_egress_port.end",
                    post_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_128_unh.step.enable_next_hop_egress_port.start",
                ),
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_fboss_cpu_remote_subnet_128_unh.step.enable_next_hop_egress_port.end",
                ),
            ],
            stages=[
                taac_thrift.Stage(
                    id="test_fboss_cpu_remote_subnet_128_unh",
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.CUSTOM_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "custom_step_name": "register_cpu_queue_static_route_patcher",
                                        "static_route_mask": 128,
                                        "next_hop_egress_port": "eth1/64/5",
                                        "patcher_name": "cpu_queue_static_route_patcher",
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                        taac_thrift.Step(
                            id="disable_next_hop_egress_port",
                            name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "enable": False,
                                        "interface_flap_method": 1,
                                        "interfaces": ["eth1/64/5"],
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            id="enable_next_hop_egress_port",
                            name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "enable": True,
                                        "interface_flap_method": 1,
                                        "interfaces": ["eth1/64/5"],
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.REGISTER_PATCHER_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.RegisterPatcherInput(
                                    register_patcher=False,
                                    name="cpu_queue_static_route_patcher",
                                    config_name="agent",
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                    ],
                )
            ],
        ),
        taac_thrift.Playbook(
            postchecks=[
                taac_thrift.PointInTimeHealthCheck(
                    name=hc_thrift.CheckName.IXIA_PACKET_LOSS_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.IxiaPacketLossHealthCheckIn(
                            clear_traffic_stats=True,
                        )
                    ),
                )
            ],
            traffic_items_to_start=["IPV6_TRAFFIC"],
            name="test_fboss_cpu_dir_conn_host_unh",
            snapshot_checks=[
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[LOW_QUEUE],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_fboss_cpu_dir_conn_host_unh.step.disable_next_hop_egress_port.end",
                    post_snapshot_checkpoint_id="stage.test_fboss_cpu_dir_conn_host_unh.step.enable_next_hop_egress_port.start",
                ),
                taac_thrift.SnapshotHealthCheck(
                    name=hc_thrift.CheckName.CPU_QUEUE_CHECK,
                    input_json=thrift_to_json(
                        hc_thrift.CpuQueueHealthCheckIn(
                            active_queues=[],
                            no_discard_queues=[HIGH_QUEUE],
                        )
                    ),
                    pre_snapshot_checkpoint_id="stage.test_fboss_cpu_dir_conn_host_unh.step.enable_next_hop_egress_port.end",
                ),
            ],
            stages=[
                taac_thrift.Stage(
                    id="test_fboss_cpu_dir_conn_host_unh",
                    steps=[
                        taac_thrift.Step(
                            name=taac_thrift.StepName.CUSTOM_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "custom_step_name": "register_cpu_queue_static_route_patcher",
                                        "static_route_mask": 64,
                                        "next_hop_egress_port": "eth1/64/5",
                                        "patcher_name": "cpu_queue_static_route_patcher",
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                        taac_thrift.Step(
                            id="disable_next_hop_egress_port",
                            name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "enable": False,
                                        "interface_flap_method": 1,
                                        "interfaces": ["eth1/64/5"],
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            id="enable_next_hop_egress_port",
                            name=taac_thrift.StepName.INTERFACE_FLAP_STEP,
                            step_params=taac_thrift.Params(
                                json_params=json.dumps(
                                    {
                                        "enable": True,
                                        "interface_flap_method": 1,
                                        "interfaces": ["eth1/64/5"],
                                    }
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.LONGEVITY_STEP,
                            step_params=taac_thrift.Params(
                                json_params='{"duration": 60}'
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.REGISTER_PATCHER_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.RegisterPatcherInput(
                                    register_patcher=False,
                                    name="cpu_queue_static_route_patcher",
                                    config_name="agent",
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_INTERRUPTION_STEP,
                            input_json=thrift_to_json(
                                taac_thrift.ServiceInterruptionInput(
                                    name=taac_thrift.Service.AGENT,
                                    trigger=taac_thrift.ServiceInterruptionTrigger.SYSTEMCTL_RESTART,
                                )
                            ),
                        ),
                        taac_thrift.Step(
                            name=taac_thrift.StepName.SERVICE_CONVERGENCE_STEP,
                        ),
                    ],
                )
            ],
        ),
    ],
)

TEST_CONFIG = test_config
