# pyre-unsafe
"""OTG L3 forwarding test config.

Exercises the full OTG backend: TestConfig -> TrafficGenerator pipeline ->
OtgTrafficGenerator -> OtgTrafficGen -> snappi.

OTG setup requirements
~~~~~~~~~~~~~~~~~~~~~~
An OTG-compatible traffic generator with at least two ports, reachable via
the snappi HTTPS API. The test is backend-agnostic — any deployment that
exposes a conformant OTG API endpoint will work:

  - ixia-c-one container (single-container, software traffic engine)
  - ixia-c multi-container (controller + separate traffic engines)
  - Keysight hardware chassis with OTG API enabled

Each OTG port must have L2 connectivity to a distinct DUT interface. The
transport between the OTG engine and the DUT is opaque to the test — direct
cable, VLAN sub-interfaces, macvlan, OVS bridges, etc. all work as long as
untagged Ethernet frames transit end-to-end between each OTG port and its
paired DUT interface.

Logical topology (two ports, two subnets):

  OTG port 1 (eth1)  <-- L2 --> DUT interface A    10.0.1.0/24
  OTG port 2 (eth2)  <-- L2 --> DUT interface B    10.0.2.0/24

DUT requirements (matching default IPs):
  Interface A: 10.0.1.2/24
  Interface B: 10.0.2.2/24
  L3 forwarding between the two subnets (static routes or connected)

The OTG endpoint addresses (10.0.x.1) and gateway IPs (10.0.x.2) are
generated by ``_subnet_ip()`` below and can be overridden by supplying
custom ``IxiaLink`` definitions to ``get_test_config()``.

Example invocation:

% export TAAC_OSS=1 TAAC_SSH_USER=root TAAC_SSH_PASSWORD=root
% ./docker/run_taac_docker.sh run python3 -m taac.runner.oss_entry_point \
      --test-configs /workspace/taac/otg/otg_basic_l3_test_config.py \
      --dut <dut> \
      --ixia-api-server https://<otg-api-host>:8443 \
      --device-info-csv /workspace/examples/topology/otg_l3_forwarding_device_info.csv \
      --circuit-info-csv /workspace/examples/topology/otg_l3_forwarding_circuit_info.csv \
      --skip-post-setup-wait
"""

import dataclasses
import os
import typing as t

from ixia.ixia import types as ixia_types
from taac.steps.step_definitions import create_longevity_step
from taac.health_check.health_check import types as hc_types  # noqa: F401
from taac.test_as_a_config import types as taac_types
from taac.test_as_a_config.types import (
    BasicPortConfig,
    BasicTrafficItemConfig,
    DeviceGroupConfig,
    DirectIxiaConnection,
    Endpoint,
    IpAddressesConfig,
    Playbook,
    PointInTimeHealthCheck,
    Stage,
    TestConfig,
    TrafficEndpoint,
)


@dataclasses.dataclass
class IxiaLink:
    """A single DUT-interface ↔ traffic-gen-port link."""
    dut_interface: str
    traffic_gen_port: str


def _subnet_ip(index: int, host: int) -> str:
    return f"10.0.{index + 1}.{host}"


def get_test_config(
    device_name: t.Optional[str] = None,
    links: t.Optional[t.List[IxiaLink]] = None,
    port_location: t.Optional[str] = None,
) -> TestConfig:
    """Generate an OTG L3 forwarding test config from link definitions.

    Each link becomes a separate OTG port with one device group. Traffic
    is routed between the first two links.

    Args:
        device_name: DUT hostname (used as endpoint name). Falls back to
                     the first entry in the TAAC_DUTS env var (set by
                     ``--dut`` in the entry point).
        links: List of IxiaLink(dut_interface, traffic_gen_port).
               If None, uses two-port defaults suitable for ixia-c loopback.
        port_location: OTG port location string override.
    """
    if device_name is None:
        duts = os.environ.get("TAAC_DUTS", "")
        if not duts:
            raise ValueError(
                "device_name not provided and TAAC_DUTS env var is not set. "
                "Pass --dut to the entry point or set TAAC_DUTS."
            )
        device_name = duts.split(",")[0]
    if links is None:
        links = [
            IxiaLink(dut_interface="port1", traffic_gen_port="eth1"),
            IxiaLink(dut_interface="port2", traffic_gen_port="eth2"),
        ]

    direct_ixia_connections = []
    basic_port_configs = []

    for i, link in enumerate(links):
        endpoint_str = f"{device_name}:{link.traffic_gen_port}"
        location = port_location or link.traffic_gen_port

        direct_ixia_connections.append(
            DirectIxiaConnection(
                interface=link.traffic_gen_port,
                ixia_port=f"1/{i + 1}",
                is_logical_port=True,
                port_location=location,
            )
        )

        dg_name = f"DG_{link.dut_interface}"

        basic_port_configs.append(
            BasicPortConfig(
                endpoint=endpoint_str,
                device_group_configs=[
                    DeviceGroupConfig(
                        device_group_index=0,
                        multiplier=1,
                        enable=True,
                        device_group_name=dg_name,
                        v4_addresses_config=IpAddressesConfig(
                            starting_ip=_subnet_ip(i, 1),
                            gateway_starting_ip=_subnet_ip(i, 2),
                            mask=24,
                        ),
                    ),
                ],
            )
        )

    src_endpoint = f"{device_name}:{links[0].traffic_gen_port}"
    dst_endpoint = f"{device_name}:{links[1].traffic_gen_port}"

    longevity_playbook = Playbook(
        name="otg_l3_forwarding",
        stages=[
            Stage(
                steps=[
                    create_longevity_step(duration=30),
                ],
            ),
        ],
        prechecks=[
            PointInTimeHealthCheck(
                name=hc_types.CheckName.WEDGE_AGENT_CONFIGURED_CHECK,
            ),
            PointInTimeHealthCheck(
                name=hc_types.CheckName.SYSTEMCTL_ACTIVE_STATE_CHECK,
                input_json='{"services": [1]}',
            ),
            PointInTimeHealthCheck(
                name=hc_types.CheckName.DEVICE_CORE_DUMPS_CHECK,
            ),
        ],
        postchecks=[
            PointInTimeHealthCheck(
                name=hc_types.CheckName.IXIA_PACKET_LOSS_CHECK,
                input_json='{"thresholds":[{"metric":3,"str_value":"0.1","expect_packet_loss":false,"comparison":3}],"sleep_time":10,"clear_traffic_stats":false}',
            ),
            PointInTimeHealthCheck(
                name=hc_types.CheckName.DEVICE_CORE_DUMPS_CHECK,
            ),
        ],
        snapshot_checks=[],
    )

    return TestConfig(
        name="OTG_L3_FORWARDING",
        basset_pool="",
        traffic_generator_backend=taac_types.TrafficGeneratorBackend.OTG,
        skip_ixia_protocol_verification=True,
        endpoints=[
            Endpoint(
                name=device_name,
                dut=True,
                direct_ixia_connections=direct_ixia_connections,
            ),
        ],
        basic_port_configs=basic_port_configs,
        basic_traffic_item_configs=[
            BasicTrafficItemConfig(
                name="routed_flow",
                traffic_type=ixia_types.TrafficType.IPV4,
                src_endpoints=[
                    TrafficEndpoint(
                        name=src_endpoint,
                        device_group_index=0,
                    ),
                ],
                dest_endpoints=[
                    TrafficEndpoint(
                        name=dst_endpoint,
                        device_group_index=0,
                    ),
                ],
                line_rate=1000,
                line_rate_type=ixia_types.RateType.FRAMES_PER_SECOND,
                bidirectional=True,
            ),
        ],
        playbooks=[longevity_playbook],
        host_os_type_map={device_name: taac_types.DeviceOsType.FBOSS},
    )


# The OSS entry point's load_test_config() looks for a module-level
# `test_config`.  When callable (not a TestConfig instance), the loader
# invokes it with no arguments.  device_name is resolved from the
# TAAC_DUTS env var, which the entry point sets from --dut before
# loading configs.
test_config = get_test_config
