// @generated SignedSource<<ae57cfad002348c9e33c96c332f5f4e5>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater neteng/taac/health_check.thrift
//
// Source: https://www.internalfb.com/code/configerator/[master]/source/neteng/taac/health_check.thrift
include "configerator/structs/neteng/qosdb/Cos.thrift"
include "thrift/annotation/thrift.thrift"

@thrift.AllowLegacyMissingUris
package;

namespace py taac.health_check.health_check
namespace py3 taac.health_check
namespace cpp2 taac.health_check

const i32 DEFAULT_HC_PRIORITY = 0;

enum HealthCheckStatus {
  UNKNOWN = 0,
  PASS = 1,
  FAIL = 2,
  ERROR = 3,
  SKIP = 4,
}

enum Scope {
  DEFAULT = 0,
  TOPOLOGY = 1,
}

enum CheckName {
  UNDEFINED = 0,
  IXIA_PACKET_LOSS_CHECK = 1,
  DSF_DRAIN_STATE_CHECK = 2,
  DSF_FABRIC_REACHABILITY_CHECK = 3,
  DSF_TRAFFIC_REBALANCE_CHECK = 4,
  NDP_CHECK = 5,
  IXIA_PORT_STATS_CHECK = 6,
  SYSTEMCTL_ACTIVE_STATE_CHECK = 8,
  WEDGE_AGENT_CONFIGURED_CHECK = 9,
  DSF_PFC_CHECK = 10,
  CORE_DUMPS_CHECK = 11,
  PORT_STATE_CHECK = 12,
  LLDP_CHECK = 13,
  IXIA_TRAFFIC_RATE_CHECK = 14,
  PFC_WD_CHCEK = 15,
  CPU_QUEUE_CHECK = 16,
  UNCLEAN_EXIT_CHECK = 17,
  MEMORY_UTILIZATION_CHECK = 18,
  BGP_SESSION_CHECK = 19,
  BGP_CONVERGENCE_CHECK = 20,
  BGP_RIB_FIB_CONSISTENCY_CHECK = 21,
  L2_ENTRY_THRESHOLD_CHECK = 22,
  PREFIX_LIMIT_CHECK = 23,
  GENERIC_ODS_CHECK = 24,
  OOMD_KILL_CHECK = 25,
  NEXT_HOP_COUNT_CHECK = 26,
  ECMP_GROUP_AND_MEMBER_COUNT_CHECK = 27,
  DEVICE_CORE_DUMPS_CHECK = 28,
  LOG_PARSING_CHECK = 29,
  BGP_SESSION_ESTABLISH_CHECK = 30,
  IXIA_PTP_CHECK = 31,
  CLEAR_COUNTERS_CHECK = 32,
  PORT_COUNTERS_CHECK = 33,
  PORT_CHANNEL_STATE_CHECK = 34,
  PORT_QUEUE_RATE_CHECK = 35,
  PORT_CHANNEL_ECMP_HASHING_CHECK = 36,
  DRAIN_STATE_CHECK = 37,
  SERVICE_RESTART_CHECK = 38,
  BGP_PEER_ROUTE_CHECK = 39,
  CPU_UTILIZATION_CHECK = 40,
  BGP_STALE_ROUTE_CHECK = 41,
  QOS_DSCP_TX_QUEUE_CHECK = 42,
  DSF_FSDB_SESSION_CHECK = 43,
  SYSTEM_CPU_LOAD_AVERAGE_CHECK = 44,
  BGP_GRACEFUL_RESTART_CHECK = 45,
  HARDWARE_CAPACITY_CHECK = 46,
  BGP_NON_BEST_PATH_CHECK = 47,
  BGP_TCPDUMP_CHECK = 48,
  BGP_ROUTE_ADVERTISEMENT_CHECK = 49,
  BGP_FIB_PROGRAMMING_CHECK = 50,
  PERIODIC_TASK_CHECK = 51,
  IBGP_PNH_METRIC_CHECK = 52,
  BGP_ROUTE_WITHDRAWAL_CHECK = 53,
  BGP_ROUTE_RESTORATION_CHECK = 54,
  PORT_SPEED_CHECK = 55,
  NEXT_HOP_GROUP_VALIDITY_CHECK = 56,
  PORT_SPEED_SNAPSHOT_CHECK = 57,
  BGP_ATTRIBUTE_VERIFICATION_CHECK = 58,
  FILE_EXISTS_HEALTH_CHECK = 59,
  UCMP_CONTROL_PLANE_CHECK = 60,
  UCMP_TRAFFIC_DISTRIBUTION_CHECK = 61,
  BGP_ROUTE_COUNT_VERIFICATION_CHECK = 62,
  PORT_FLAP_CHECK = 63,
  BGP_WEIGHT_BY_PEER_TYPE_CHECK = 64,
  ROUTE_CONVERGENCE_TIME_CHECK = 65,
  DLB_RESOURCE_STICKINESS_CHECK = 66,
  FSDB_SUBSCRIBER_TIMESTAMP_CHECK = 67,
  BUFFER_UTILIZATION_CHECK = 68,
}

enum Service {
  WEDGE_AGENT = 1,
  BGPD = 2,
  QSFP_SERVICE = 3,
  FSDB = 4,
  OPENR = 5,
  FBOSS_SW_AGENT = 6,
  FBOSS_HW_AGENT_0 = 7,
  FBOSS_HW_AGENT_1 = 8,
}

const map<Service, string> SERVICE_NAME_MAP = {
  WEDGE_AGENT: "wedge_agent",
  BGPD: "bgpd",
  QSFP_SERVICE: "qsfp_service",
  FSDB: "fsdb",
  OPENR: "openr",
  FBOSS_SW_AGENT: "fboss_sw_agent",
  FBOSS_HW_AGENT_0: "fboss_hw_agent@0",
  FBOSS_HW_AGENT_1: "fboss_hw_agent@1",
};

enum PacketLossMetric {
  DURATION = 1,
  FRAME_DELTA = 2,
  PERCENTAGE = 3,
}

enum ThresholdType {
  ABSOLUTE = 1,
  PERCENT = 2,
}

enum TrafficRateMetric {
  TX_RATE = 1,
  RX_RATE = 2,
}

const map<PacketLossMetric, string> PACKET_LOSS_METRIC_MAP = {
  DURATION: "packet_loss_duration",
  FRAME_DELTA: "frame_delta",
  PERCENTAGE: "packet_loss_percentage",
};

enum ComparisonType {
  LESS_THAN = 0,
  GREATER_THAN = 1,
  EQUAL_TO = 2,
  LESS_THAN_EQUAL_TO = 3,
  GREATER_THAN_EQUAL_TO = 4,
  BETWEEN = 5,
}

enum Priority {
  PRIORITY_0 = 0,
  PRIORITY_1 = 1,
  PRIORITY_2 = 2,
  PRIORITY_3 = 3,
  PRIORITY_4 = 4,
  PRIORITY_5 = 5,
  PRIORITY_6 = 6,
  PRIORITY_7 = 7,
}

struct PriorityRateThreshold {
  1: Priority priority = PRIORITY_2;
  2: ComparisonType comparison = GREATER_THAN;
  3: i64 rate_percent = 0;
}

struct PortQueueRateThreshold {
  1: list<string> interfaces;
  2: list<PriorityRateThreshold> priority_rate_thresholds; // List of thresholds per TC
}

struct PortQueueRateHealthCheckIn {
  1: list<PortQueueRateThreshold> thresholds;
}

struct DsfPfcThreshold {
  1: list<string> interfaces;
  2: ComparisonType comparison = EQUAL_TO;
  3: optional i64 in_pfc;
  4: optional i64 out_pfc;
  5: Priority priority = Priority.PRIORITY_2;
}

struct PfcWdThreshold {
  1: list<string> interfaces;
  2: ComparisonType comparison = GREATER_THAN;
  3: i64 deadlock_threshold = 0;
  4: i64 recovery_threshold = 0;
}

struct PortCountersHealthCheckIn {
  1: list<PortCountersThreshold> thresholds;
}

struct PortCountersThreshold {
  1: list<string> interfaces;
  2: ComparisonType comparison = EQUAL_TO;
  3: optional i64 in_discards;
  4: optional i64 out_discards;
  5: optional i64 in_error;
  6: optional i64 out_error;
}

struct PacketLossThreshold {
  1: optional list<string> names;
  4: string str_value = "0";
  5: optional string lower_bound; // applicable if comparison is BETWEEN
  6: optional string upper_bound;
  3: PacketLossMetric metric = PacketLossMetric.DURATION;
  7: bool expect_packet_loss = false; // if packet loss is expected, fail the check if packet loss is not observed
  8: ComparisonType comparison = LESS_THAN_EQUAL_TO;
}

struct PacketLossViolation {
  1: string name;
  2: string str_value;
  3: PacketLossThreshold threshold;
}

const map<TrafficRateMetric, string> TRAFFIC_RATE_MAP = {
  TX_RATE: "tx_rate",
  RX_RATE: "rx_rate",
};

struct TrafficRateThreshold {
  1: optional list<string> names;
  2: i64 value = 0;
  3: ThresholdType threshold_type = ThresholdType.PERCENT;
  4: TrafficRateMetric metric = TrafficRateMetric.TX_RATE;
}

struct BaseHealthCheckIn {}

struct IxiaPacketLossHealthCheckIn {
  1: list<PacketLossThreshold> thresholds;
  2: i32 sleep_time = 10;
  3: bool clear_traffic_stats;
}

struct DsfTrafficRebalanceHealthCheckIn {
  1: i32 deviation_threshold_pct = 1; # in percentage;
}

struct SystemctlActiveStateHealthCheckIn {
  1: optional list<Service> services;
}

struct DsfDrainStateCheckIn {
  1: bool is_drained = false;
}

struct DsfPfcHealthCheckIn {
  1: list<DsfPfcThreshold> thresholds;
  2: bool clear_counters = false;
}

struct IxiaTrafficRateHealthCheckIn {
  1: list<TrafficRateThreshold> thresholds;
}

struct PfcWdHealthCheckIn {
  1: list<PfcWdThreshold> thresholds;
  2: bool clear_counters = false;
}

struct CpuQueueHealthCheckIn {
  // queues expected to experience increased in out-traffic
  1: list<i32> active_queues;
  2: optional list<i32> no_discard_queues;
  3: optional list<i32> active_discard_queues;
  // queues expected to not experience any increase in out-traffic
  4: optional list<i32> inactive_queues;
  // Minimum increase in out pps required for a queue to be considered "active." Defaults to 100 pps
  10: i32 active_min_out_pps = 100;
  11: optional map<i32, i32> active_min_out_pps_per_queue;
}

struct QoSDscpTxQueueHealthCheckIn {
  1: list<TxQueueInfo> tx_queue_info_list;
}

struct TxQueueInfo {
  1: string hostname;
  2: string interface;
  3: list<Cos.ClassOfService> cos_list;
  // check output bytes by default
  4: string key_desc = "out_bytes.sum.60";
  // The difference (x2 - x1) is compared to 'val' using 'comparison' (e.g., GREATER_THAN, LESS_THAN)
  5: i64 val;
  6: ComparisonType comparison = GREATER_THAN;
  7: bool enforce_exclusivity = true;
}

struct BufferUtilizationThreshold {
  1: string hostname;
  2: list<string> interfaces;
  3: list<Cos.ClassOfService> active_cos_list;
  4: i64 active_queue_max_bytes;
  5: i64 other_queue_max_bytes;
}

struct BufferUtilizationHealthCheckIn {
  1: list<BufferUtilizationThreshold> thresholds;
}

struct HealthCheckResult {
  1: CheckName name;
  2: HealthCheckStatus status;
  3: optional string message;
}
