// @generated SignedSource<<9070f3eb0d61990fc1af6a6825ba8ee2>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater neteng/taac/test_as_a_config.thrift
namespace py taac.taac
namespace py3 taac
namespace cpp2 facebook.taac

include "configerator/structs/neteng/taac/health_check.thrift"
include "configerator/structs/neteng/ixia/ixia.thrift"
include "thrift/annotation/thrift.thrift"

@thrift.AllowLegacyMissingUris
package;

struct PointInTimeHealthCheck {
  // name of the health check
  1: health_check.CheckName name;
  2: optional string input_json;
  3: optional i32 priority;
  4: optional health_check.Scope check_scope;
  5: optional Params check_params;
  6: optional string check_id;
}

struct SnapshotHealthCheck {
  1: health_check.CheckName name;
  2: optional string input_json;
  3: optional health_check.Scope check_scope;
  4: optional string pre_snapshot_checkpoint_id;
  5: optional string post_snapshot_checkpoint_id;
  6: optional string check_id;
  7: optional Params check_params;
}

struct Stage {
  # required if concurrent is set to False
  1: list<Step> steps = [];
  2: bool concurrent = false;
  3: i32 iteration = 1;
  4: optional string id;
  5: optional string description;
  # if true, the stage will stop executing if any step fails.
  # This means that any step after the failed step will not be executed
  6: bool terminate_on_step_failure = false;
  # required if concurrent is set to True
  7: optional list<ConcurrentStep> concurrent_steps;

  // Field 100 (netwhoami_scope) removed — use device_regexes or attribute_filters instead.
  101: optional list<string> device_regexes;
  // OSS-compatible attribute-based device filtering.
  // Keys are SwitchAttributes field names (e.g., "role", "operating_system", "hardware").
  // Values are lists of allowed values. A device matches if ALL keys match (AND logic).
  102: optional map<string, list<string>> attribute_filters;
}
struct Step {
  1: StepName name;
  3: optional string input_json;
  5: optional string description;
  6: optional string id;
  7: optional Params step_params;
  8: i32 retryable_num = 0;
  9: i32 retryable_delay = 0;
  10: i32 delay = 0;

  // Field 100 (netwhoami_scope) removed — use device_regexes or attribute_filters instead.
  101: optional list<string> device_regexes;
  // OSS-compatible attribute-based device filtering.
  102: optional map<string, list<string>> attribute_filters;
}

struct ConcurrentStep {
  1: list<Step> steps;
  2: i32 iteration = 1;
}

struct BaseInput {}

struct ValidationInput {
  1: list<PointInTimeHealthCheck> point_in_time_checks;
  10: optional ValidationStage stage;
  11: bool fail_fast = false;
}

struct DrainUndrainInput {
  1: DrainHandler drain_handler = DrainHandler.NDS;
  3: bool drain;
}

struct SystemRebootInput {
  1: SystemRebootTrigger trigger;
}

struct ServiceInterruptionInput {
  1: Service name;
  2: ServiceInterruptionTrigger trigger;
  3: bool create_cold_boot_file = false;
  4: optional list<string> agents;
}

struct ServiceConvergenceInput {
  1: list<Service> services = [
    Service.BGP,
    Service.AGENT,
    Service.QSFP_SERVICE,
    Service.FSDB,
  ];
  2: i32 timeout = 300;
  3: map<Service, i32> service_convergence_timeout;
}

struct CustomStepInput {
  1: string custom_step_name;
}

struct RegisterPatcherInput {
  1: string name;
  2: bool register_patcher = true;
  3: bool persistent = true;
  4: string config_name;
  5: optional string py_func_name;
  6: optional map<string, string> kwargs;
  7: optional string description;
  // Field 8 (py_patcher) removed — use py_func_name + kwargs instead.
  9: bool do_warmboot = false;
}

struct RunTaskInput {
  1: Task task;
  2: bool blocking = true; # wait for task execution completion before moving on to the next step
}

enum StepName {
  UNDEFINED = 0,
  DUMMY_STEP = 1,
  VALIDATION_STEP = 2,
  RUN_SSH_COMMAND_STEP = 3,
  DRAIN_UNDRAIN_STEP = 4,
  INTERFACE_FLAP_STEP = 5,
  LONGEVITY_STEP = 6,
  SYSTEM_REBOOT_STEP = 7,
  SERVICE_CONVERGENCE_STEP = 9,
  SERVICE_INTERRUPTION_STEP = 10,
  REGISTER_PATCHER_STEP = 11,
  INVOKE_IXIA_API_STEP = 12,
  ALLOCATE_CGROUP_SLICE_MEMORY_STEP = 13,
  RUN_TASK_STEP = 14,
  TOGGLE_IXIA_PREFIX_SESSION_FLAP = 15,
  MASS_BGP_PEER_TOGGLE = 16,
  ECMP_MEMBER_STATIC_ROUTE = 17,
  VERIFY_PORT_OPERATIONAL_STATE = 18,
  VERIFY_PORT_SPEED = 19,
  REGISTER_SPEED_FLIP_PATCHER = 20,
  REGISTER_PORT_CHANNEL_MIN_LINK_PERCENTAGE_PATCHERS = 21,
  MODULE_POWER_TOGGLE_STEP = 22,
  INJECT_ROUTES_STEP = 23,
  VERIFY_FILE_MODIFICATION_TIME_STEP = 24,
  PROFILING_STEP = 25,
  CUSTOM_STEP = 1001,
}

enum Service {
  AGENT = 1,
  BGP = 2,
  QSFP_SERVICE = 3,
  FSDB = 4,
  OPENR = 5,
  FBOSS_SW_AGENT = 6,
  FBOSS_HW_AGENT_0 = 7,
  FBOSS_HW_AGENT_1 = 8,
  ARISTA_SYSTEM_AGENT = 9,
  ARISTA_L3_FORWARDING_AGENT = 10,
  ARISTA_FABRIC_AGENT = 11,
  ARISTA_ROUTING_AGENT = 12,
  ARISTA_EBRA = 13,
  ARISTA_XCVR_AGENT = 14,
  COOP = 15,
  ARISTA_CUSTOM_AGENTS = 16,
}

const map<Service, string> SERVICE_NAME_MAP = {
  AGENT: "wedge_agent",
  BGP: "bgpd",
  QSFP_SERVICE: "qsfp_service",
  FSDB: "fsdb",
  OPENR: "openr",
  FBOSS_SW_AGENT: "fboss_sw_agent",
  FBOSS_HW_AGENT_0: "fboss_hw_agent@0",
  FBOSS_HW_AGENT_1: "fboss_hw_agent@1",
  ARISTA_SYSTEM_AGENT: "DummySystemAgent",
  ARISTA_L3_FORWARDING_AGENT: "DummyForwardingAgent",
  ARISTA_FABRIC_AGENT: "DummyFabricAgent",
  ARISTA_ROUTING_AGENT: "Rib",
  ARISTA_EBRA: "Ebra",
  ARISTA_XCVR_AGENT: "XcvrAgent",
  COOP: "coop",
  ARISTA_CUSTOM_AGENTS: "CustomAgents",
};

enum ValidationStage {
  PRE_TEST = 1,
  MID_TEST = 2,
  POST_TEST = 3,
  SNAPSHOT = 4,
}

enum DrainHandler {
  NDS = 1,
  LOCAL_DRAINER = 2,
}

enum InterfaceFlapMethod {
  THRIFT_PORT_STATE_CHANGE = 1,
  FBOSS_WEDGE_QSFP_UTIL_TX = 2,
  FBOSS_WEDGE_QSFP_UTIL_POWER = 3,
  SSH_PORT_STATE_CHANGE = 4,
}

enum SystemRebootTrigger {
  FULL_SYSTEM_REBOOT = 1,
  BMC_POWER_RESET = 2,
  BMC_MICROSERVER_ONLY_RESET = 3,
}

enum ServiceInterruptionTrigger {
  SYSTEMCTL_STOP = 1,
  SYSTEMCTL_START = 2,
  SYSTEMCTL_RESTART = 3,
  CRASH = 4,
}

enum ApplyPatcherMethod {
  AGENT_RELOAD = 1,
  AGENT_WARMBOOT = 2,
  AGENT_RELOAD_AND_WARMBOOT = 3,
  BGP_RESTART = 4,
}

struct Task {
  1: string task_name;
  2: Params params;
  // if true, the task will be executed after ixia setup
  // and an instance of Ixia will be available to the task
  4: bool ixia_needed = false;
  5: optional string hostname;
  6: optional string description;

  # DEPRECATED: use ixia_needed instead
  3: bool run_post_ixia_setup = false;
}

union ParamValue {
  1: string string_value;
  2: list<string> string_list;
  3: bool boolean_value;
  4: i64 int_value;
}

struct Params {
  1: optional map<string, ParamValue> static_params;
  2: optional string json_params;
  3: optional map<string, string> jq_params;
  4: optional map<string, list<TransformFunction>> transform_params;
  // param name to cache id mapping. Cached params can be accessed via jq_params later in the test
  5: optional map<string, string> cache_params;
}

struct TransformFunction {
  1: string name;
  3: optional map<string, ParamValue> static_params;
  4: optional string json_params;
}

struct PeriodicTask {
  1: string name;
  2: Task task;
  3: i32 interval = 0;
  4: optional i32 max_runtime;
  5: optional bool terminate_on_error;
  6: bool retryable = true;
  // If provided, each element in params_list will be passed to the task in sequential order:
  // the first iteration uses params_list[0], the second uses params_list[1], and so on.
  7: optional list<Params> params_list;
  8: i32 exception_sleep_time = 60;
}

struct TestInterface {
  1: string interface_name;
  2: string display_name;
  3: string switch_name;
  8: SwitchAttributes switch_attributes;

  4: optional string neighbor_switch_name;
  5: optional string neighbor_interface_name;
  6: optional string neighbor_display_name;
  9: optional SwitchAttributes neighbor_switch_attributes;
  // DSF specific fields
  7: optional string slot_name;
}

struct SwitchAttributes {
  // Field 1 (netwhoami) removed — use flat fields below.
  2: list<string> tags;

  // Flat fields — OSS-compatible, no netwhoami dependency.
  10: string device_name = "";
  11: string role = "";
  12: string operating_system = "";
  13: string hardware = "";
  14: string ai_zone = "";
}

// OSS-compatible mock device info - uses strings instead of netwhoami enums.
// Use this with oss_mock_device_data in TestConfig.
struct MockDeviceInfo {
  1: string name = "";
  2: string hardware = ""; // e.g., "ARISTA_7516", "MONTBLANC"
  3: string role = ""; // e.g., "EB", "FSW", "RSW"
  4: string operating_system = ""; // e.g., "EOS", "FBOSS"
  5: string dc = ""; // e.g., "ash6"
  6: string region = ""; // e.g., "ash"
  7: i64 asset_id = 0;
  8: string asic = ""; // e.g., "MEMORY"
  9: string routing_protocol = ""; // e.g., "BGP"
  10: string dc_type = ""; // e.g., "ONE", "TWO"
  11: string network_area = ""; // e.g., "BACKBONE"
  12: string network_type = ""; // e.g., "EBB"
}

struct SnakeConfig {
  1: string source;
  2: string destination;
  3: string source_ip;
  4: string destination_ip;
}

enum PrefixPatternType {
  INCREMENT = 0,
  CUSTOM = 1,
  RANDOM_MASK = 2,
}

struct RandomMaskConfig {
  1: string fixed_value;
  2: string mask_value;
  3: optional i32 seed;
  4: optional i32 count;
}

struct RouteScale {
  1: string starting_prefixes;
  2: optional string prefix_name;
  3: optional i32 prefix_length;
  4: optional string prefix_step;
  5: i32 multiplier = 10;
  6: i32 prefix_count = 1000;
  7: ixia.IpAddressFamily ip_address_family = ixia.IpAddressFamily.IPV6;
  8: optional list<list<i32>> as_path_prepend_numbers;
  9: list<string> bgp_communities;
  10: optional ixia.BgpFlapConfig prefix_flap_config;
  11: optional ixia.DistributedPrefixLengthConfig distributed_prefix_length_config;
  12: PrefixPatternType pattern_type = PrefixPatternType.INCREMENT;
  13: optional RandomMaskConfig random_mask_config;
  14: optional list<string> extended_bgp_communities;
}

struct RouteScaleSpec {
  1: optional RouteScale v6_route_scale;
  2: optional RouteScale v4_route_scale;
  3: i32 multiplier = 1;
  4: i32 network_group_index;
}

struct IpAddressesConfig {
  1: optional string starting_ip;
  2: optional string increment_ip;
  3: optional string gateway_starting_ip;
  4: optional string gateway_increment_ip;
  5: optional i32 mask;
  6: optional i32 start_index;
}

struct BgpConfig {
  1: optional i32 local_as;
  2: optional bool enable_4_byte_local_as;
  3: optional i64 local_as_4_bytes;
  4: optional bool is_confed;
  5: optional list<RouteScaleSpec> route_scales;
  6: list<ixia.BgpCapability> bgp_capabilities = [
    ixia.BgpCapability.IpV4Unicast,
    ixia.BgpCapability.IpV6Unicast,
  ];
  7: bool enable_graceful_restart = true;
  8: i32 graceful_restart_timer = 120;
  9: bool advertise_end_of_rib = true;
  10: optional ixia.BgpFlapConfig peer_flap_config;
  11: optional i32 local_as_increment;
  12: optional ixia.BgpPeerType bgp_peer_type;
  13: optional string local_peer_starting_ip;
  14: optional string local_peer_increment_ip;
  15: optional string remote_peer_starting_ip;
  16: optional string remote_peer_increment_ip;
  17: optional list<ixia.ImportBgpRoutesParams> import_bgp_routes_params_list;
  18: optional string bgp_peer_name;
  19: optional list<ixia.CustomNetworkGroupConfig> custom_network_group_configs;
  # AS Set Mode - controls how local AS is included in AS_PATH
  # Use DO_NOT_INCLUDE_LOCAL_AS to simulate route-server behavior
  # where the peer doesn't add its AS to the AS_PATH
  20: optional ixia.BgpAsSetMode as_set_mode;
  21: i32 hold_timer = 30;
  22: i32 keepalive_timer = 10;
}

struct DeviceGroupConfig {
  1: i32 device_group_index;
  2: optional i32 multiplier;
  3: optional IpAddressesConfig v6_addresses_config;
  4: optional IpAddressesConfig v4_addresses_config;
  5: optional BgpConfig v6_bgp_config;
  6: optional BgpConfig v4_bgp_config;
  7: bool enable = true;
  8: optional string tag_name;
  9: optional string device_group_name;
}

struct BasicPortConfig {
  1: optional string endpoint;
  2: optional ixia.L1Config l1_config;
  3: optional list<DeviceGroupConfig> device_group_configs;
}

struct DirectIxiaConnection {
  1: string interface;
  2: string ixia_port;
  3: optional string ixia_chassis_ip;
  4: bool is_logical_port = true;
}

struct Endpoint {
  1: string name;
  2: optional list<DirectIxiaConnection> direct_ixia_connections;
  3: optional bool ixia_needed;
  4: optional list<string> ixia_ports;
  5: bool dut = false;
  6: optional string mac_address;
  // Field 7 (nic_type) removed — ETH0 is always used.
  8: optional list<string> exclude_ixia_ports;
}

struct TrafficEndpoint {
  1: string name;
  2: i32 device_group_index;
  3: optional i32 network_group_index;
}

struct BasicTrafficItemConfig {
  1: list<TrafficEndpoint> src_endpoints;
  2: list<TrafficEndpoint> dest_endpoints;
  3: ixia.TrafficType traffic_type = ixia.TrafficType.IPV6;
  4: i32 line_rate = 10;
  5: ixia.RateType line_rate_type = ixia.RateType.PERCENT_LINE_RATE;
  6: optional list<ixia.TrafficStatsTrackingType> tracking_types;
  7: optional ixia.FrameSize frame_size_settings;
  8: bool bidirectional = true;
  9: bool merge_destinations = false;
  10: bool allow_self_destined = false;
  11: ixia.SrcDestMeshType src_dest_mesh = ixia.SrcDestMeshType.ONE_TO_ONE;
  12: ixia.RouteMeshType route_mesh = ixia.RouteMeshType.ROUTE_ONE_TO_ONE;
  13: bool full_mesh = false;
  14: optional string name;
  15: optional list<PacketHeader> packet_headers;
  16: optional ixia.QoSConfig qos_config;
  17: bool enabled = true;
  18: optional bool skip_default_l4_protocol;
}

struct TrafficItemSettings {
  1: optional i32 line_rate;
  2: optional ixia.RateType line_rate_type;
  3: optional ixia.FrameSize frame_size_settings;
  4: optional ixia.QoSConfig qos_config;
}

enum DataType {
  SCALAR = 1,
  LIST = 2,
}

enum ReferenceType {
  SRC_IPV6_ADDRESS = 1,
  DST_IPV6_ADDRESS = 2,
  SRC_MAC_ADDRESS = 3,
  DST_MAC_ADDRESS = 4,
  SRC_GATEWAY_IPV6_ADDRESS = 5,
  DST_GATEWAY_IPV6_ADDRESS = 6,
  SRC_IPV4_ADDRESS = 7,
  DST_IPV4_ADDRESS = 8,
  SRC_GATEWAY_IPV4_ADDRESS = 9,
  DST_GATEWAY_IPV4_ADDRESS = 10,
  DST_LINK_LOCAL_IPV6_ADDRESS = 11,
}

struct Reference {
  1: ReferenceType type;
  2: DataType data_type = DataType.SCALAR;
  3: list<i32> indices = [0];
  4: i32 device_group_index = 0;
}

struct Field {
  1: ixia.Query query;
  2: string attrs_json;
  3: optional map<string, Reference> references;
}

struct PacketHeader {
  1: ixia.Query query;
  2: optional ixia.Query append_to_query;
  3: optional list<Field> fields;
  4: bool remove_from_stack = false;
}

struct Playbook {
  1: string name;
  2: list<Stage> stages;
  3: optional string description;
  4: i32 iteration = 1;
  5: optional list<string> traffic_items_to_start;
  6: bool enabled = true;
  7: bool backup_and_restore_ixia_config = false;
  // Field 9 (scope) removed — use device_regexes or attribute_filters instead.
  10: optional list<PointInTimeHealthCheck> prechecks;
  11: optional list<PointInTimeHealthCheck> postchecks;
  12: optional list<SnapshotHealthCheck> snapshot_checks;
  13: bool skip_test_config_prechecks = false;
  14: bool skip_test_config_postchecks = false;
  15: bool skip_test_config_snapshot_checks = false;
  16: bool override_duplicate_checks = true;
  17: optional list<health_check.CheckName> prechecks_to_skip;
  18: optional list<health_check.CheckName> postchecks_to_skip;
  23: optional list<health_check.CheckName> snapshot_checks_to_skip;
  19: optional list<string> check_ids_to_skip;
  20: optional list<Step> cleanup_steps;
  25: optional list<Step> setup_steps;
  21: optional list<string> device_regexes;
  22: optional list<PeriodicTask> periodic_tasks;
  // OSS-compatible attribute-based device filtering.
  27: optional map<string, list<string>> attribute_filters;
  24: optional map<string, TrafficItemSettings> traffic_items_to_configure;
  26: optional string scuba_table;
}

struct TestConfig {
  1: string name;
  2: string basset_pool;
  3: list<Playbook> playbooks;
  4: list<Service> rsyslog_services = [
    Service.AGENT,
    Service.QSFP_SERVICE,
    Service.BGP,
    Service.FSDB,
  ];
  5: optional map<string, Service> rsyslog_services_overrides;
  // Field 6 (rsyslog_services_overrides_by_role) removed — use rsyslog_services_overrides with device name keys instead.
  7: bool ignore_circuit_fbnet_status = false;
  8: bool ignore_down_circuits = true;
  9: list<Endpoint> endpoints;
  10: optional list<string> traffic_items_to_start;
  11: optional list<Task> setup_tasks;
  12: optional list<Task> teardown_tasks;
  13: optional list<PeriodicTask> periodic_tasks;
  14: optional list<BasicTrafficItemConfig> basic_traffic_item_configs;
  15: optional list<BasicPortConfig> basic_port_configs;
  16: optional BasicPortConfig default_basic_port_config;
  17: optional list<ixia.TrafficItem> user_defined_traffic_items;
  18: optional list<SnakeConfig> snake_configs;
  19: optional bool skip_advertised_prefixes_check;
  20: bool skip_ixia_protocol_verification = false;
  21: i32 ixia_protocol_verification_timeout = 90;
  22: optional list<PointInTimeHealthCheck> prechecks;
  23: optional list<PointInTimeHealthCheck> postchecks;
  24: optional list<SnapshotHealthCheck> snapshot_checks;
  25: optional list<string> netcastle_cli_args;
  26: optional list<string> tags;
  27: optional list<ixia.PTPConfig> ptp_configs;
  28: i32 basset_reservation_time_hr = 4;
  29: i32 log_collection_timeout = 180;
  // Field 30 (mock_netwhoami_data) removed — use oss_mock_device_data instead.
  31: optional map<string, DeviceOsType> host_os_type_map;
  32: optional list<PointInTimeHealthCheck> startup_checks;
  33: optional map<string, string> host_driver_args;
  34: optional string scuba_table;
  // OSS-compatible mock device data - uses strings instead of netwhoami types.
  35: optional map<string, MockDeviceInfo> oss_mock_device_data;
}

enum DeviceOsType {
  FBOSS = 1,
  ARISTA_OS = 2,
  # Arista device running FBOSS routing stack
  ARISTA_FBOSS = 3,
  CISCO = 4,
  IOSXR = 5,
}
