// @generated SignedSource<<0c9d09011686e442af383a721f3941e1>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater neteng/ixia/ixia.thrift
include "thrift/annotation/thrift.thrift"

@thrift.AllowLegacyMissingUris
package;

namespace cpp2 facebook.ixia
namespace py ixia
namespace php ixia
namespace go ixia
namespace rust ixia_thrift
namespace py3 ixia

################################################################################
# NOTE for N00bs: All struct field with default values are implicitly optional
# Sample Config (10/22/19): P119544133
################################################################################

enum ApiServerOsType {
  LINUX = 0,
  WINDOWS = 1,
}

enum IpAddressFamily {
  IPV4 = 0,
  IPV6 = 1,
}

const map<TrafficType, string> TRAFFIC_TYPE_MAP = {
  TrafficType.IPV4: "ipv4",
  TrafficType.IPV6: "ipv6",
  TrafficType.RAW: "raw",
};

enum BgpCapability {
  IpV4Unicast = 0,
  IpV6Unicast = 1,
  RouteRefresh = 2,
  IpV4Multicast = 3,
  IpV4MulticastVpn = 4,
  IpV6Mpls = 5,
  IpV6MplsVpn = 6,
  IpV6Multicast = 7,
  IpV6MulticastVpn = 8,
  Ipv4UnicastAddPath = 9,
  Ipv6UnicastAddPath = 10,
  LinkStateNonVpn = 11,
  NHEncodingCapabilities = 12,
  RouteConstraint = 13,
  SRTEPoliciesV4 = 14,
  SRTEPoliciesV6 = 15,
  Vpls = 16,
  ipv4UnicastFlowSpec = 17,
  ipv6UnicastFlowSpec = 18,
  IpV4MplsVpn = 19,
}

# Combination that is used to uniquely identify any IXIA port in our network
struct PhyPortConfig {
  1: string chassis_ip;
  2: i16 slot_number;
  3: i16 port_number;
}

struct IPv4AddressInfo {
  1: string starting_ip;
  2: i16 subnet_mask = 24;
  3: string increment_ip = "0.0.0.1";
  4: string gateway_starting_ip;
  5: string gateway_increment_ip = "0.0.0.0";
  6: optional i32 start_index;
}

struct IPv6AddressInfo {
  1: string starting_ip;
  2: i16 subnet_mask = 64;
  3: string increment_ip = "0:0:0:0:0:0:0:1";
  4: string gateway_starting_ip;
  5: string gateway_increment_ip = "0:0:0:0:0:0:0:0";
  6: optional i32 start_index;
}

struct IpAddresses {
  1: optional IPv6AddressInfo ipv6_addresses_config;
  2: optional IPv4AddressInfo ipv4_addresses_config;
}

enum EndpointType {
  IXIA_PORT = 0,
  BGP_PREFIX = 1,
}

struct Endpoint {
  1: string port_name;
  2: EndpointType endpoint_type = EndpointType.IXIA_PORT;
  # Will be used if the traffic source or destination endpoint is a BGP prefix
  # instead of a physical IXIA port
  3: optional string bgp_prefix_name;

  # Will be used if the traffic endpoint is a BGP prefix or IXIA port
  4: i32 device_group_index;
  # Will be used if the traffic endpoint is a BGP prefix
  # instead of a physical IXIA port
  5: optional i32 network_group_index;
}

enum RateType {
  # bitsPerSecond|framesPerSecond|interPacketGap|percentLineRate
  # NOTE: For now, only PERCENT_LINE_RATE is supported
  PERCENT_LINE_RATE = 0,
  // BITS_PER_SECOND = 1
  FRAMES_PER_SECOND = 2,
// INTER_PACKET_GAP = 3
}

const map<RateType, string> RATE_TYPE_MAP = {
  // BITS_PER_SECOND: "bitsPerSecond",
  FRAMES_PER_SECOND: "framesPerSecond",
  // INTER_PACKET_GAP: "interPacketGap",
  PERCENT_LINE_RATE: "percentLineRate",
};

struct TrafficRateInfo {
  1: RateType rate_type = RateType.PERCENT_LINE_RATE;
  2: i32 rate_value;
}

enum TransportProtocol {
  UDP = 0,
  TCP = 1,
}

const map<TransportProtocol, string> TRANSPORT_PROTOCOL_MAP = {
  UDP: "UDP",
  TCP: "TCP",
};

struct L4ProtocolConfig {
  1: TransportProtocol protocol = TransportProtocol.TCP;
  2: i32 src_port_start_value = 10000;
  3: i32 src_port_increment_value = 1;
  4: i32 src_port_count_value = 1000;
  5: i32 dst_port_start_value = 20000;
  6: i32 dst_port_increment_value = 1;
  7: i32 dst_port_count_value = 1000;
}

struct MPLSConfig {
  1: list<i32> label_value = [16];
  3: i32 time_to_live = 64;
  4: i32 experimental = 0;
}

enum QueryType {
  DISPLAY_NAME = 1,
  STACK_TYPE_ID = 2,
  TEMPLATE_NAME = 3,
}

const map<QueryType, string> QUERY_TYPE_MAP = {
  DISPLAY_NAME: "DisplayName",
  STACK_TYPE_ID: "StackTypeId",
  TEMPLATE_NAME: "TemplateName",
};

union AttrValue {
  1: string str;
  2: i32 integer;
  3: list<string> str_list;
  4: list<i32> integer_list;
  5: bool boolean;
}

struct Attr {
  1: string name;
  2: AttrValue value;
}

struct Query {
  1: string regex;
  2: QueryType query_type = QueryType.DISPLAY_NAME;
}

struct Field {
  1: Query query;
  2: list<Attr> attrs;
}

struct PacketHeader {
  1: Query query;
  2: optional list<Field> fields;
  3: optional Query append_to_query;
  4: bool remove_from_stack = false;
}

struct TrafficItem {
  1: optional string name;
  2: list<Endpoint> source_endpoints;
  3: list<Endpoint> dest_endpoints;
  4: TrafficRateInfo traffic_rate_info;
  5: TrafficFlowConfig traffic_flow_config;
  6: optional L4ProtocolConfig l4_protocol_config;
  # TTL/Hop Limit
  7: optional HopLimitConfig hoplimit_config;
  8: optional MPLSConfig mpls_config;
  9: bool enabled = true;
  10: optional list<PacketHeader> packet_headers;
  11: TrafficType traffic_type;
  12: optional QoSConfig qos_config;
}

struct PortConfig {
  # Must be unique to identify an IXIA port in the entire topology. This will
  # be used to refer src/dst end points while configuring traffic items
  1: string port_name;
  2: string description = "";
  3: PhyPortConfig phy_port_config;
  4: i16 device_multiplier = 1;
  5: list<DeviceGroupConfig> device_group_configs;
  6: optional L1Config l1_config;
}

struct DeviceGroupConfig {
  1: i32 device_group_index;
  2: i16 multiplier = 1;
  3: IpAddresses ip_addresses_config;
  4: optional BgpConfigInfo bgp_config;
  5: bool enable = true;
  6: optional string tag_name;
  7: optional string device_group_name;
}

struct IxiaConfig {
  1: string api_server_ip;
  2: ApiServerOsType api_server_platform_type = ApiServerOsType.WINDOWS;
  3: list<PortConfig> port_configs;
  4: list<TrafficItem> traffic_items;
  5: list<PTPConfig> ptp_configs;
}

##############################
# BGP CONFIG RELATED STRUCTS #
##############################

enum BgpPeerType {
  IBGP = 0,
  EBGP = 1,
}

const map<BgpPeerType, string> BGP_PEER_TYPE_MAP = {
  IBGP: "internal",
  EBGP: "external",
};

# BGP AS Set Mode - controls how local AS is included in AS_PATH
# This is used to control IXIA's behavior when sending BGP updates
enum BgpAsSetMode {
  # Include local AS as AS_SEQUENCE (default eBGP behavior)
  INCLUDE_LOCAL_AS_AS_SEQ = 0,
  # Include local AS as AS_SEQUENCE for confederation
  INCLUDE_LOCAL_AS_AS_SEQ_CONFED = 1,
  # Include local AS as AS_SET
  INCLUDE_LOCAL_AS_AS_SET = 2,
  # Include local AS as AS_SET for confederation
  INCLUDE_LOCAL_AS_AS_SET_CONFED = 3,
  # Do not include local AS in AS_PATH (for route-server simulation)
  DO_NOT_INCLUDE_LOCAL_AS = 4,
  # Prepend local AS to first segment
  PREPEND_LOCAL_AS_TO_FIRST_SEGMENT = 5,
}

const map<BgpAsSetMode, string> BGP_AS_SET_MODE_MAP = {
  BgpAsSetMode.INCLUDE_LOCAL_AS_AS_SEQ: "includelocalasasasseq",
  BgpAsSetMode.INCLUDE_LOCAL_AS_AS_SEQ_CONFED: "includelocalasasasseqconfederation",
  BgpAsSetMode.INCLUDE_LOCAL_AS_AS_SET: "includelocalasasasset",
  BgpAsSetMode.INCLUDE_LOCAL_AS_AS_SET_CONFED: "includelocalasasassetconfederation",
  BgpAsSetMode.DO_NOT_INCLUDE_LOCAL_AS: "dontincludelocalas",
  BgpAsSetMode.PREPEND_LOCAL_AS_TO_FIRST_SEGMENT: "prependlocalastofirstsegment",
};

struct BgpFlapConfig {
  1: i16 uptime_in_sec;
  2: i16 downtime_in_sec;
}

struct BgpPeerConfig {
  1: optional i32 local_as;
  2: BgpPeerType peer_type = BgpPeerType.EBGP;
  3: string local_peer_starting_ip;
  4: string local_peer_increment_ip;
  5: string remote_peer_starting_ip;
  6: string remote_peer_increment_ip;
  7: bool enable_graceful_restart = false;
  // @lint-ignore LINEWRAP
  8: list<BgpCapability> capabilities = [
    BgpCapability.IpV4Unicast,
    BgpCapability.IpV6Unicast,
  ];
  9: optional BgpFlapConfig peer_flap_config;
  10: optional bool advertise_end_of_rib;
  11: optional i32 graceful_restart_timer;
  12: optional bool is_confed;
  13: optional i64 local_as_4_bytes;
  14: bool enable_4_byte_local_as = true;
  15: i32 local_as_increment = 0;
  16: optional string bgp_peer_name;
  17: optional BgpAsSetMode as_set_mode;
  18: optional i32 hold_timer;
  19: optional i32 keepalive_timer;
}

enum PrefixLengthDistributionAlgorithmType {
  PERCENTAGE = 0,
  WEIGHTED = 1,
  AUTOEVEN = 2,
  AUTOGEOMETRIC = 3,
}

const map<
  PrefixLengthDistributionAlgorithmType,
  string
> PREFIX_LENGTH_DISTRIBUTED_ALGORITHM_MAP = {
  PrefixLengthDistributionAlgorithmType.PERCENTAGE: "percentage",
  PrefixLengthDistributionAlgorithmType.WEIGHTED: "weighted",
  PrefixLengthDistributionAlgorithmType.AUTOEVEN: "autoEven",
  PrefixLengthDistributionAlgorithmType.AUTOGEOMETRIC: "autoGeometric",
};

enum PrefixLengthDistributionModeType {
  # The custom distribution algo will be applied on all the prefixes for the entire device group
  PERDEVICE = 0,
  # The custom distribution algo will be applied on all the prefixes for the entire topology obj
  PERTOPOLOGY = 1,
  # The custom distribution algo will be applied on all the prefixes for the entire ixia port
  PERPORT = 2,
}

const map<
  PrefixLengthDistributionModeType,
  string
> PREFIX_LENGTH_DISTRIBUTED_MODE_MAP = {
  PrefixLengthDistributionModeType.PERDEVICE: "perDevice",
  PrefixLengthDistributionModeType.PERTOPOLOGY: "perTopology",
  PrefixLengthDistributionModeType.PERPORT: "perPort",
};

struct DistributedPrefixLengthConfig {
  # Algorithm to use for custom distribution of prefix length
  1: PrefixLengthDistributionAlgorithmType algorithm;
  # Mode to use for custom distribution of prefix length
  2: PrefixLengthDistributionModeType mode;
  # Value map to use for custom distribution of prefix length.
  # Key is prefix length and its value is its weightage.
  3: map<i16, i16> prefix_length_value_weight_map;
}

struct BgpPrefixConfig {
  1: string prefix_name;
  2: string starting_ip;
  # Increment for IP address between different clients
  3: string increment_ip;
  # Use when single valued prefix length for all ixia advertised bgp prefixes is desired
  # It has precedence over DistributedPrefixLengthConfig
  4: optional i16 prefix_length;
  # Number of prefixes per client
  5: i32 count;
  6: optional BgpFlapConfig prefix_flap_config;
  7: optional BgpCommunity bgp_community;
  8: optional AsPathPrepend as_path_prepend;
  14: optional list<AsPathPrepend> as_path_prepends;
  9: optional list<BgpCommunity> bgp_communities;
  # Use when custom distribution pattern is required to be used for bgp prefix lengths.
  10: optional DistributedPrefixLengthConfig distributed_prefix_length_config;
  # Address family is included in the prefix config as well, as we should be able to
  # advertise v4 prefixes over v6 peers
  11: optional IpAddressFamily ip_address_family;
  12: i32 network_group_index;
  13: i32 multiplier;
  15: optional string prefix_pool_name;
  16: optional list<ExtendedBgpCommunity> extended_bgp_communities;
}

enum BgpRouteImportFileType {
  CSV = 0,
  JUNIPER = 1,
  CISCO = 2,
  ARISTA = 3,
  NOKIA = 4,
}

const map<BgpRouteImportFileType, string> BGP_ROUTE_IMPORT_FILE_TYPE_MAP = {
  BgpRouteImportFileType.CSV: "csv",
  BgpRouteImportFileType.JUNIPER: "juniper",
  BgpRouteImportFileType.CISCO: "cisco",
  BgpRouteImportFileType.ARISTA: "arista",
  BgpRouteImportFileType.NOKIA: "nokia",
};

enum BgpRouteDistributionType {
  ROUND_ROBIN = 0,
  REPLICATE = 1,
}

const map<BgpRouteDistributionType, string> BGP_ROUTE_DISTRIBUTION_TYPE_MAP = {
  BgpRouteDistributionType.ROUND_ROBIN: "roundRobin",
  BgpRouteDistributionType.REPLICATE: "replicate",
};

enum BgpNextHopModificationType {
  OVER_WRITE_TESTERS_ADDRESS = 0,
  PRESERVE_FROM_FILE = 1,
}

const map<
  BgpNextHopModificationType,
  string
> BGP_NEXT_HOP_MODIFICATION_TYPE_MAP = {
  BgpNextHopModificationType.OVER_WRITE_TESTERS_ADDRESS: "overwriteTestersAddress",
  BgpNextHopModificationType.PRESERVE_FROM_FILE: "preserveFromFile",
};

enum SetNextHopType {
  SAME_AS_LOCAL_IP = 0,
  MANUALLY = 1,
}

const map<SetNextHopType, string> SET_NEXT_HOP_TYPE_MAP = {
  SetNextHopType.SAME_AS_LOCAL_IP: "sameaslocalip",
  SetNextHopType.MANUALLY: "manual",
};

struct ImportBgpRoutesParams {
  1: string bgp_route_import_file_path;
  2: BgpRouteImportFileType import_file_type;
  3: bool import_only_best_routes = true;
  4: BgpRouteDistributionType bgp_route_distribution_type = BgpRouteDistributionType.ROUND_ROBIN;
  5: optional i32 route_limit;
  6: BgpNextHopModificationType bgp_next_hop_modification_type = BgpNextHopModificationType.OVER_WRITE_TESTERS_ADDRESS;
  7: i32 network_group_index;
  8: optional list<BgpAttributeConfig> bgp_attribute_configs;
  9: i32 multiplier;
  10: optional string prefix_pool_name;
  11: optional i32 start_index;
  12: optional i32 end_index;
  13: optional SetNextHopType set_next_hop_type;
  14: optional IpAddressFamily set_next_hop_ip_type;
}

enum DistribitionType {
  ROUND_ROBIN = 0,
  RANDOMIZE = 1,
}

enum BgpAttribute {
  COMMUNITIES = 0,
  EXT_COMMUNITIES = 1,
}

struct BgpAttributeConfig {
  1: BgpAttribute attribute;
  2: DistribitionType distribution_type;
  3: optional list<list<string>> value_lists;
  4: optional string file_path;
  # applicable only for COMMUNITIES and EXT_COMMUNITIES
  5: optional BgpCommunityType bgp_community_type;
}

enum BgpCommunityType {
  NOEXPORT = 0,
  NOADVERTISED = 1,
  NOEXPORT_SUBCONFED = 2,
  MANUAL = 3,
  // For details about LLGR options - refer http://docs.frrouting.org/en/latest/bgp.html
  LLGR_STALE = 4,
  NO_LLGR = 5,
}

const map<BgpCommunityType, string> BGP_COMMUNITY_TYPE_MAP = {
  BgpCommunityType.NOEXPORT: "noexport",
  BgpCommunityType.NOADVERTISED: "noadvertised",
  BgpCommunityType.NOEXPORT_SUBCONFED: "noexport_subconfed",
  BgpCommunityType.MANUAL: "manual",
  BgpCommunityType.LLGR_STALE: "llgr_stale",
  BgpCommunityType.NO_LLGR: "no_llgr",
};

struct BgpCommunity {
  1: BgpCommunityType bgp_community_type;
  // For ex., as_number would be '65000' in '65000:100'
  2: i64 as_number;
  // For ex., last_two_octets would be '100' in '65000:100'
  3: i64 last_two_octets;
}

enum ExtendedBgpCommunityType {
  LINK_BW = 0,
}

const map<ExtendedBgpCommunityType, string> EXTENDED_BGP_COMMUNITY_TYPE_MAP = {
  ExtendedBgpCommunityType.LINK_BW: "link_bandwidth",
};

struct ExtendedBgpCommunity {
  1: ExtendedBgpCommunityType type;
  // 1 octet, 0x04 for Link-Bandwidth
  2: byte sub_type;
  // 2 octets, operator-assigned value, e.g. 16-bit AS number
  3: i16 global_as_number;
  // 4 octets, bandwidth in bytes/sec (IEEE 754 float32)
  4: i32 local_bw_value;
}

struct AsPathPrepend {
  // For ex., [65000, 65000]
  1: list<i64> as_numbers;
}

struct CustomNetworkGroupConfig {
  1: string device_group_name;
  2: string network_group_name;
  3: i32 network_group_multiplier;
  4: string prefix_start_value;
  5: i32 prefix_length;
  6: string nexthop_start_value;
  7: string nexthop_increments;
  8: i32 ecmp_width;
  9: i32 number_of_addresses_per_row = 1;
  10: list<string> community_list = [];
  11: string next_hop_type = "manual";
  12: string next_hop_ip_type = "ipv6";
  13: string next_hop_increment_mode = "fixed";
  14: i32 network_group_index;
}

struct BgpConfig {
  1: IpAddressFamily ip_address_family;
  2: BgpPeerConfig bgp_peer_config;
  3: optional list<BgpPrefixConfig> bgp_prefix_configs;
  4: optional list<ImportBgpRoutesParams> import_bgp_routes_params_list;
  5: optional list<CustomNetworkGroupConfig> custom_network_group_configs;
}

struct BgpConfigInfo {
  1: optional BgpConfig bgp_v4_config;
  2: optional BgpConfig bgp_v6_config;
}

#######################################
# TRAFFIC ITEM CONFIG RELATED STRUCTS #
#######################################

enum TransmissionControlType {
  # auto|burstFixedDuration|continuous|custom|fixedDuration|fixedFrameCount|fixedIterationCount
  # NOTE: Only CONTINUOUS mode is supported as of now
  CONTINUOUS = 0,
  FIXED_DURATION = 1,
  FIXED_FRAME_COUNT = 2,
}

const map<TransmissionControlType, string> TRANS_CONTROL_TYPE_MAP = {
  CONTINUOUS: "continuous",
  FIXED_DURATION: "fixedDuration",
  FIXED_FRAME_COUNT: "fixedFrameCount",
};

struct TransmissionControl {
  1: TransmissionControlType type = TransmissionControlType.CONTINUOUS;
  # Will be used for FIXED_FRAME_COUNT mode
  2: i32 frame_count = 10000;
  # Will be used for FIXED_DURATION mode. Unit in seconds
  3: i32 duration = 300; # in seconds
}

enum FramePayloadPattern {
  # decrementByte|decrementWord|incrementByte|incrementWord|random
  INCREMENT_BYTE = 0,
  INCREMENT_WORD = 1,
  DECREMENT_BYTE = 2,
  DECREMENT_WORD = 3,
  RANDOM = 4,
}

const map<FramePayloadPattern, string> FRAME_PAYLOAD_PATTERN_MAP = {
  INCREMENT_BYTE: "incrementByte",
  INCREMENT_WORD: "incrementWord",
  DECREMENT_BYTE: "decrementByte",
  DECREMENT_WORD: "decrementWord",
  RANDOM: "random",
};

enum RateDistributionType {
  # applyRateToAll|splitRateEvenly
  APPLY_RATE_TO_ALL = 0,
  SPLIT_RATE_EVENLY = 1,
}

const map<RateDistributionType, string> RATE_DIS_TYPE_MAP = {
  APPLY_RATE_TO_ALL: "applyRateToAll",
  SPLIT_RATE_EVENLY: "splitRateEvenly",
};

struct RateDistribution {
  // @lint-ignore LINEWRAP
  1: RateDistributionType port_rate_distribution = RateDistributionType.APPLY_RATE_TO_ALL; # noqa: B950
  // @lint-ignore LINEWRAP
  2: RateDistributionType flowgroups_rate_distribution = RateDistributionType.SPLIT_RATE_EVENLY; # noqa: B950
}

enum SrcDestMeshType {
  # fullMesh|manyToMany|none|oneToOne
  FULL_MESH = 0,
  MANY_TO_MANY = 1,
  NONE = 2,
  ONE_TO_ONE = 3,
}

const map<SrcDestMeshType, string> SRC_DEST_MESH_MAP = {
  FULL_MESH: "fullMesh",
  MANY_TO_MANY: "manyToMany",
  NONE: "none",
  ONE_TO_ONE: "oneToOne",
};

enum RouteMeshType {
  # fullMesh|oneToOne
  ROUTE_ONE_TO_ONE = 0,
  ROUTE_FULL_MESH = 1,
}

const map<RouteMeshType, string> ROUTE_MESH_MAP = {
  ROUTE_ONE_TO_ONE: "oneToOne",
  ROUTE_FULL_MESH: "fullMesh",
};

enum TransmitModeType {
  # interleaved|sequential
  INTERLEAVED = 0,
  SEQUENTIAL = 1,
}

const map<TransmitModeType, string> TRANSMIT_MODE_MAP = {
  INTERLEAVED: "interleaved",
  SEQUENTIAL: "sequential",
};

enum CrcType {
  # badCrc|goodCrc
  GOOD_CRC = 0,
  BAD_CRC = 1,
}

const map<CrcType, string> CRC_TYPE_MAP = {
  GOOD_CRC: "goodCrc",
  BAD_CRC: "badCrc",
};

enum FrameSizeType {
  # auto|fixed|increment|presetDistribution|quadGaussian|random|weightedPairs
  FIXED = 0,
  INCREMENT = 1,
  CUSTOM_IMIX = 2,
  RANDOM = 3,
}

const map<FrameSizeType, string> FRAME_SIZE_TYPE_MAP = {
  FIXED: "fixed",
  INCREMENT: "increment",
  CUSTOM_IMIX: "weightedPairs",
  FrameSizeType.RANDOM: "random",
};

struct FrameSize {
  1: FrameSizeType type = FrameSizeType.FIXED;
  # Used by FrameSizeType.FIXED mode
  2: i16 fixed_size = 400;
  # Used by FrameSizeType.INCREMENT mode
  3: i16 increment_from = 64;
  # Used by FrameSizeType.INCREMENT mode
  4: i16 increment_step = 100;
  # Used by FrameSizeType.INCREMENT mode
  5: i16 increment_to = 1500;
  # Used by FrameSizeType.CUSTOM_IMIX mode
  # defines farame size to weight mapping
  6: map<i16, i16> imix_weight = {128: 2, 1000: 1, 9000: 1};
  7: optional i16 random_min;
  8: optional i16 random_max;
}

enum TrafficStatsTrackingType {
  TRAFFIC_ITEM = 0,
  FLOW_GROUP = 1,
  SRC_DEST_ENDPOINT_PAIR = 2,
  SRC_DEST_VALUE_PAIR = 3,
  TCP_DST_PORT = 4,
  IPV6_DST_ADDR = 5,
  UDP_SRC_PORT = 6,
  UDP_DST_PORT = 7,
}

const map<TrafficStatsTrackingType, string> TRAFFIC_STATS_TRACKING_TYPE_MAP = {
  TRAFFIC_ITEM: "trackingenabled0",
  FLOW_GROUP: "flowGroup0",
  SRC_DEST_ENDPOINT_PAIR: "sourceDestEndpointPair0",
  SRC_DEST_VALUE_PAIR: "sourceDestValuePair0",
  TCP_DST_PORT: "tcpTcpDstPrt0",
  IPV6_DST_ADDR: "ipv6DestIp0",
  UDP_SRC_PORT: "udpUdpSrcPrt0",
  UDP_DST_PORT: "udpUdpDstPrt0",
};

struct TrafficFlowConfig {
  # TODO: Setting CRC type support is missing as IXIA RestPy has not yet
  #  implemented it, unlike the low level APIs
  1: TransmissionControl transmission_control;
  2: RateDistribution rate_distribution;
  3: FrameSize frame_size;
  // @lint-ignore LINEWRAP
  4: FramePayloadPattern frame_payload_pattern = FramePayloadPattern.INCREMENT_BYTE;
  5: SrcDestMeshType src_dest_mesh = SrcDestMeshType.MANY_TO_MANY;
  6: RouteMeshType route_mesh = RouteMeshType.ROUTE_FULL_MESH;
  7: bool allow_self_destined = false;
  8: bool bidirectional = true;
  9: bool merge_destinations = false;
  10: TransmitModeType transmit_mode = TransmitModeType.INTERLEAVED;
  11: CrcType crc_type = CrcType.GOOD_CRC;
  # By default, TrafficStatsTrackingType.TRAFFIC_ITEM will always be enabled
  12: list<TrafficStatsTrackingType> tracking_types;
}

enum PHBTypes {
  # TRAFFIC CLASS is the DS field for IPv6
  # Rest of the fields signify the various ways
  # to specify DS values for IPv4 https://fburl.com/wda68475
  DEFAULT = 0,
  CLASSSELECTOR = 1,
  AF = 2,
  EF = 3,
  TRAFFIC_CLASS = 4,
}

# Maps PHBtypes to IXIA Rest API strings
const map<PHBTypes, string> DSCP_MAP = {
  DEFAULT: "Default PHB",
  CLASSSELECTOR: "Class selector",
  AF: "Assured forwarding PHB",
  EF: "Expedited forwarding PHB",
  TRAFFIC_CLASS: "Traffic Class",
};

# TTL/Hop Limit config for IXIA packet generation API
struct HopLimitConfig {
  1: i32 value;
}

struct PTPEndpoint {
  1: string name;
  2: i32 device_group_index = 0;
}

enum PTPCommunicationMode {
  MULTICAST = 0,
  UNICAST = 1,
  MIXEDMODE = 2,
}

const map<PTPCommunicationMode, string> PTP_COMMUNICATION_MODE_MAP = {
  MULTICAST: "multicast",
  UNICAST: "unicast",
  MIXEDMODE: "mixedmode",
};

enum PTPStepMode {
  SINGLE_STEP = 0,
  TWO_STEP = 1,
}

const map<PTPStepMode, string> PTP_STEP_MODE_MAP = {
  SINGLE_STEP: "singlestep",
  TWO_STEP: "twostep",
};

struct PTPConfig {
  5: PTPEndpoint server_endpoint;
  6: list<PTPEndpoint> client_endpoints;
  3: PTPCommunicationMode communication_mode = PTPCommunicationMode.UNICAST;
  4: PTPStepMode step_mode = PTPStepMode.TWO_STEP;
  # DEPRECATED
  1: optional string server_port_name;
  # DEPRECATED
  2: optional list<string> client_port_name_list;
}

enum PfcQueue {
  ZERO = 0,
  ONE = 1,
  TWO = 2,
  THREE = 3,
  FOUR = 4,
  FIVE = 5,
  SIX = 6,
  SEVEN = 7,
  NONE = 999,
}

const map<PfcQueue, string> PFC_QUEUE_MAP = {
  PfcQueue.NONE: "-1",
  ZERO: "0",
  ONE: "1",
  TWO: "2",
  THREE: "3",
  FOUR: "4",
  FIVE: "5",
  SIX: "6",
  SEVEN: "7",
};

enum FlowControlType {
  IEEE_802_1_QBB = 1,
  IEEE_802_3X = 2,
}

const map<FlowControlType, string> FLOW_CONTROL_TYPE_MAP = {
  IEEE_802_1_QBB: "ieee802.1Qbb",
  IEEE_802_3X: "ieee802.3x",
};

struct PfcPriorityGroupsConfig {
  1: PfcQueue priority0_pfc_queue = PfcQueue.ZERO;
  2: PfcQueue priority1_pfc_queue = PfcQueue.ONE;
  3: PfcQueue priority2_pfc_queue = PfcQueue.TWO;
  4: PfcQueue priority3_pfc_queue = PfcQueue.THREE;
  5: PfcQueue priority4_pfc_queue = PfcQueue.NONE;
  6: PfcQueue priority5_pfc_queue = PfcQueue.NONE;
  7: PfcQueue priority6_pfc_queue = PfcQueue.NONE;
  8: PfcQueue priority7_pfc_queue = PfcQueue.NONE;
}

struct FlowControlConfig {
  1: optional bool enable_pfc_pause_delay;
  2: optional PfcPriorityGroupsConfig pfc_prority_groups_config;
  3: optional FlowControlType flow_control_type;
}

struct L1Config {
  1: bool enable_fcoe = false;
  2: optional FlowControlConfig flow_control_config;
}

enum TrafficType {
  IPV4 = 1,
  IPV6 = 2,
  RAW = 3,
}

enum EcnCapability {
  ECN_CAPABLE = 1,
  ECN_NON_CAPABLE = 2,
  MIXED = 3,
}

# QoS config for IXIA packet generation API
struct QoSConfig {
  # Default PHBType is Traffic class for IPv6
  # Other values can be specified for IPv4 from
  # DSCP_MAP
  1: PHBTypes phb_type = PHBTypes.TRAFFIC_CLASS;
  # Specific value for DSCP that a packet must be
  # marked with. This value will be modified if
  # packet type is IPv6
  2: i32 dscp_value;
  # Olympic QoS Queue Name
  3: EcnCapability ecn_capability = EcnCapability.ECN_NON_CAPABLE;
}
